### ISSUE TITLE
Error with PlayerChangePlotEvent

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#2278]
Originally reported on Google Code with ID 2256

```
What steps will reproduce the problem?
I have no idea

What is the expected output? :
Not sure

What do you see instead? :
[21:29:54] [Server thread/ERROR]: Could not pass event PlayerChangePlotEvent to Towny
v0.89.2.7
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerMoveChunk(TownyPlayerListener.java:770)
[Towny-0.89.2.7.jar:?]
    at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerMove(TownyPlayerListener.java:553)
[Towny-0.89.2.7.jar:?]
    at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:255) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.PacketPlayInPositionLook.a(SourceFile:18) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
    at com.palmergames.bukkit.towny.ChunkNotification.getTownPVPNotification(ChunkNotification.java:195)
~[?:?]
    at com.palmergames.bukkit.towny.ChunkNotification.getNotificationContent(ChunkNotification.java:138)
~[?:?]
    at com.palmergames.bukkit.towny.ChunkNotification.getNotificationString(ChunkNotification.java:112)
~[?:?]
    at com.palmergames.bukkit.towny.listeners.TownyCustomListener.onPlayerChangePlotEvent(TownyCustomListener.java:54)
~[?:?]
    at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c3c767f-33d5de3]
    ... 23 more
What is your Towny version number? :
0.89.2.7

What is your TownyChat version number? :
0.4.2

What is your Bukkit version number? :
Spigot 1.8.3, buildtools.jar of 1 May

What operating system? :
Mac OS X 10.9.5 (server)
Windows 8.1 Pro x64 (Client)
Error is on server in the console

Please use pastebin.com to link the following files:
- Your full server startup from server.log,
http://pastebin.com/wSRX6yqu

- Your towny config.yml (if using MySQL please remove pasword,)
http://pastebin.com/eWpHUFPC

- Your townyperms.yml,
http://pastebin.com/uUqC94ZG

- Your permissions file.
http://pastebin.com/srQxCjLG bPermissions

In the case of chat-issues please link your:
- Chatconfig.yml
http://pastebin.com/Wi5UaK7P

- Channels.yml
http://pastebin.com/5v0YnpUL

Skipping these files is not an option. It is the easiest way to diagnose an
issue ticket properly. If you do skip this step then your ticket will most
likely be deleted and you will be asked to resubmit.




```

Reported by `FPSUsername@outlook.com` on 2015-03-29 19:43:32

**Comment by Klawdek** [comment]
> ```
> See the instructions I gave in the duplicated thread.
> ```
> 
> Reported by `LlmDlio` on 2015-03-29 20:48:18
> 
> * **Status changed**: `Duplicate`
> * **Merged into**: #2236

No duplicates of this error contain an answer they are all rejected for missing information.
