### ISSUE TITLE
When town delete, Freezing server.

### ISSUE THREAD

**Issue by B4TT3RY** [TownyAdvanced/Towny#2954]
### What steps will reproduce the problem?
1. town delete (revert on claim is turn on)
2. freeze server
3. normalize after 1 minute

### What is the expected output?
1. react plugin's error

### What is your Towny version?
Do not say "latest".
0.91.4.12 (Neder/Towny, Custon language(Korean))

### What is your spigot/craftbukkit version?
Do not say "latest".
PaperSpigot 1.12.2 (git-Paper-1436)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/QjvaVbzz
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/wSeM85fQ
3. Your townyperms.yml : https://pastebin.com/UGB7Pmpq
4. Your log's error : https://pastebin.com/M56LDQSr

**Comment by LlmDl** [comment]
Your server probably cannot handle large towns being deleted while the revert on unclaim is turned on.  Or react monitor is being too cautious and Towny isn't actually freezing the server. 

I don't think you're using my Towny anyways, since your startup is showing translated sections which I did not translate.

**Comment by B4TT3RY** [comment]
That towny is almost same source code your towny. just translated.
when i claim 34 chunks and delete town, 20~30 seconds freeze server.
i'm using on E3-1230v5, SSD. what's problem?

**Comment by LlmDl** [comment]
Does it freeze the same when react monitor are not used?

**Comment by B4TT3RY** [comment]
yep

![image](https://user-images.githubusercontent.com/12368101/41194139-f1351d00-6c51-11e8-84f4-3e87e1ca2919.png)

**Comment by LlmDl** [comment]
That says your uptime is 21.9 hours. Stop teh server, remove react, start the server and test again.

**Comment by B4TT3RY** [comment]
```
[02:06:58] [Server thread/INFO]: [Towny] Enabling Towny v0.91.4.12
[02:06:58] [Server thread/INFO]: ====================      타우니      ========================
[02:06:58] [Server thread/INFO]: [타우니] Database: [로드] mysql [저장] mysql
[02:06:58] [Server thread/WARN]: [com.palmergames.bukkit.towny.log] [타우니] 오류: SQL: Load Town unknown Error - 
[02:06:58] [Server thread/WARN]: com.palmergames.bukkit.towny.exceptions.AlreadyRegisteredException: B4TT3RY__은/는 이미 test (정착지)의 일부입니다. (first test town name is "test", second test town name is "B4TT3RY", i don't know why that error is happening.)
[02:06:58] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.object.Town.addResidentCheck(Town.java:206)
[02:06:58] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.object.Town.addResident(Town.java:192)
[02:06:58] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.db.TownySQLSource.loadTown(TownySQLSource.java:777)
[02:06:58] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.db.TownyDataSource.loadTowns(TownyDataSource.java:247)
[02:06:58] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.db.TownyDataSource.loadAll(TownyDataSource.java:99)
[02:06:58] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.object.TownyUniverse.loadDatabase(TownyUniverse.java:326)
[02:06:58] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.object.TownyUniverse.loadSettings(TownyUniverse.java:277)
[02:06:58] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.Towny.load(Towny.java:216)
[02:06:58] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:112)
[02:06:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:06:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[02:06:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[02:06:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[02:06:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[02:06:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[02:06:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[02:06:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[02:06:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293)
[02:06:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[02:06:58] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[02:06:58] [Server thread/INFO]: [Towny] Loading Error: Could not read town data B4TT3RY'.
[02:06:58] [Server thread/INFO]: [타우니] 오류: 로드 실패! (fail load)
[02:06:58] [Server thread/INFO]: [com.palmergames.bukkit.towny.log] =============================================================
[02:06:58] [Server thread/INFO]: [com.palmergames.bukkit.towny.log] [경고] - ***** 안전 모드 ***** 0.91.4.12 (turn on safe mode)
[02:06:58] [Server thread/INFO]: [com.palmergames.bukkit.towny.log] =============================================================
```

```
[02:07:59] [Server thread/INFO]: [Towny] Enabling Towny v0.91.4.12
[02:07:59] [Server thread/INFO]: ====================      타우니 (Towny)     ========================
[02:07:59] [Server thread/INFO]: [타우니] Database: [로드(Load)] mysql [저장(Save)] mysql
[02:08:00] [Server thread/WARN]: [com.palmergames.bukkit.towny.log] [타우니] 오류: SQL: Load world unknown error - 
[02:08:00] [Server thread/WARN]: com.palmergames.bukkit.towny.exceptions.NotRegisteredException: 마을 'test'은(는) 등록되지 않았습니다. (Town 'test' is not registered.)
[02:08:00] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.db.TownyDatabaseHandler.getTown(TownyDatabaseHandler.java:142)
[02:08:00] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.db.TownySQLSource.loadWorld(TownySQLSource.java:1062)
[02:08:00] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.db.TownyDataSource.loadWorlds(TownyDataSource.java:269)
[02:08:00] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.db.TownyDataSource.loadAll(TownyDataSource.java:99)
[02:08:00] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.object.TownyUniverse.loadDatabase(TownyUniverse.java:326)
[02:08:00] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.object.TownyUniverse.loadSettings(TownyUniverse.java:277)
[02:08:00] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.Towny.load(Towny.java:216)
[02:08:00] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:112)
[02:08:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:08:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[02:08:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[02:08:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[02:08:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[02:08:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[02:08:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[02:08:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[02:08:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293)
[02:08:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[02:08:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[02:08:00] [Server thread/INFO]: [Towny] Loading Error: Could not read world data 'world'.
[02:08:00] [Server thread/INFO]: [타우니] 오류: 로드 실패! (Failed Load)
[02:08:00] [Server thread/INFO]: [com.palmergames.bukkit.towny.log] =============================================================
[02:08:00] [Server thread/INFO]: [com.palmergames.bukkit.towny.log] [경고] - ***** 안전 모드 ***** 0.91.4.12 (turn on safe mode)
[02:08:00] [Server thread/INFO]: [com.palmergames.bukkit.towny.log] =============================================================
```

and i'll tested without react. wait plz

**Comment by B4TT3RY** [comment]
[02:16:05] [Server thread/INFO]: B4TT3RY__ issued server command: /t delete
[02:16:06] [Server thread/INFO]: B4TT3RY__ issued server command: /accept
[02:16:14] [Server thread/INFO]: [com.palmergames.bukkit.towny.log] [전체 메시지] 마을 test 이(가) 몰락하였습니다! (town test is deleted)

without react, freezing 8 seconds

![image](https://user-images.githubusercontent.com/12368101/41194313-7c193cec-6c54-11e8-9a2d-e465e82b74b0.png)

**Comment by LlmDl** [comment]
Which command are you using to claim the chunks? /t claim auto?

**Comment by B4TT3RY** [comment]
nope
/t claim -> move -> /t claim -> move -> /t claim  . . . - > /t claim -> /t delete -> /accept

**Comment by LlmDl** [comment]
Since it's going over each chunk (30+ in your tests) and checking if there are blocks that need to be reverted it will take some time. The plot snapshots are stored in flatfile even if you use mysql. I can't make this work any faster, so it's just the case that your hardware is bottlenecked.

**Comment by B4TT3RY** [comment]
So you can not load the data asynchronously or freeze the server?

**Comment by B4TT3RY** [comment]
```
[12:00:24] [Craft Scheduler Thread - 2636/WARN]: [Towny] Plugin Towny v0.91.4.12 generated an exception while executing task 92
java.lang.NullPointerException: null
	at com.palmergames.bukkit.towny.db.TownyDatabaseHandler.removeTown(TownyDatabaseHandler.java:497) ~[?:?]
	at com.palmergames.bukkit.towny.tasks.DailyTimerTask.collectTownCosts(DailyTimerTask.java:355) ~[?:?]
	at com.palmergames.bukkit.towny.tasks.DailyTimerTask.run(DailyTimerTask.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1436]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1436]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1436]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```
It seems that the village should not disappear due to the error. (Google translate)

**Comment by LlmDl** [comment]
Your NPE is happening on this line:

```
saveResidentList();
```
Is there something up with your residents in the town you're testing on? What is your MC account name?

**Comment by B4TT3RY** [comment]
When I do a town delete test, Only me.

maybe yes
