### ISSUE TITLE
BUG townyadmin purge

### ISSUE THREAD

**Issue by andfont** [TownyAdvanced/Towny#3061]
version de towny 0.93 for 1.13, does not work the purge commands I pass the log:
townyadmin purge 40
[13:21:39 WARN]: Unexpected exception while parsing console command "townyadmin purge 40"
org.bukkit.command.CommandException: Unhandled exception executing command 'townyadmin' in plugin Towny v0.93.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-f6a273b-7a2f486]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-f6a273b-7a2f486]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot.jar:git-Spigot-f6a273b-7a2f486]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:684) [spigot.jar:git-Spigot-f6a273b-7a2f486]
        at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:459) [spigot.jar:git-Spigot-f6a273b-7a2f486]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [spigot.jar:git-Spigot-f6a273b-7a2f486]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-f6a273b-7a2f486]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-f6a273b-7a2f486]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at com.palmergames.bukkit.towny.command.TownyAdminCommand.purge(TownyAdminCommand.java:889) ~[?:?]
        at com.palmergames.bukkit.towny.command.TownyAdminCommand.parseTownyAdminCommand(TownyAdminCommand.java:204) ~[?:?]
        at com.palmergames.bukkit.towny.command.TownyAdminCommand.onCommand(TownyAdminCommand.java:114) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-f6a273b-7a2f486]
        ... 8 more

**Comment by LlmDl** [comment]
Skipped form. Resubmit.
