### ISSUE TITLE
BUG: townyadmin purge <days>

### ISSUE THREAD

**Issue by andfont** [TownyAdvanced/Towny#3093]
It does not work when executing the command townyadmin purge 40 for example gives error

What steps will reproduce the problem?
1.Do /townyadmin purge 40

What is the expected output?

Deleting all inactive users on the server that have not connected at that time are completely removed from the server

What is your Towny version?

The issue occurs both on 0.92.0.0 and 0.93.0.0.

The problem occurs in the version: 0.93.0.0 in previous versions works well

CraftBukkit version git-Spigot-2086bb0-d0a3620 (MC: 1.13.1) (Implementing API version 1.13.2-R0.2-SNAPSHOT)

Please use Pastebin.com to link the following files:
16:54:11 INFO]: [MineBackup]  * saving worlds\atracciones
>townyadmin purge 40
[16:54:22 WARN]: Unexpected exception while parsing console command "townyadmin purge 40"
org.bukkit.command.CommandException: Unhandled exception executing command 'townyadmin' in plugin Towny v0.93.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:684) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:459) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at com.palmergames.bukkit.towny.command.TownyAdminCommand.purge(TownyAdminCommand.java:889) ~[?:?]
        at com.palmergames.bukkit.towny.command.TownyAdminCommand.parseTownyAdminCommand(TownyAdminCommand.java:204) ~[?:?]
        at com.palmergames.bukkit.towny.command.TownyAdminCommand.onCommand(TownyAdminCommand.java:114) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
        ... 8 more

(optional) If this is to do with permissions,
 It does not have all the permissions it does not have to do with permissions if not a major bug!

(optional) If this is to do with chat,

**Comment by andfont** [comment]
please any news is going to make a new compilation with the solution? Thank you

**Comment by LlmDl** [comment]
Figured this out, the command doesn't work when run from console but does work fine when run ingame by an admin player.

Fix is coming, the confirmation system will have to be able to support console questions.

**Comment by andfont** [comment]
thank you I hope the solution as soon as possible! xD also wanted to comment if it were updated to 1.14.1, we already know that it has many problems of terrible slowness but we hope that "MOJAN" of a hotfix xD for that reason we would like to know if it was updated to 1.14.1 thanks xD

**Comment by LlmDl** [comment]
Use this @andfont Towny 0.93.1.0 ( https://cdn.discordapp.com/attachments/321710042091094026/580758574393982977/Towny.jar ) See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf

**Comment by andfont** [comment]
also works for version 1.14.1? Thanks xD

**Comment by LlmDl** [comment]
yes

**Comment by andfont** [comment]
Hello friend, since I have put this version on my server 1.14.3, I have problems with plots, every day I put them on sale with cost 0 and people have money to pay but always take them away, what can it be? Is it a bug? thanks greetings.

**Comment by LlmDl** [comment]
It costs 0 but they don't pay 0? I don't think I understand you, sorry.

**Comment by andfont** [comment]
no no, for example they buy a plot for 10 of money the next day they lose the plot! and it goes on sale at cost 0, he throws them out of their plot and they have money to pay for the taxa. in summary the next day when I restart the server it takes them out of their plot :(

**Comment by LlmDl** [comment]
File a new ticket, that is a separate issue from this one.

**Comment by LlmDl** [comment]
Done: https://github.com/TownyAdvanced/Towny/commit/6f00a982951960fb256da667fd2928fcfd839811
