### ISSUE TITLE
Sometimes heavy console spam 

### ISSUE THREAD

**Issue by Feldmarschall** [TownyAdvanced/Towny#3094]
Hello, i have sometimes an error spam with the new towny version. 
There was no problem with the last version.

### What is your Towny version?

Towny v0.93.0.0

### What is your spigot/craftbukkit version?

[11:46:47 INFO]: This server is running CraftBukkit version git-Spigot-f6a273b-db10914 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
 

```
[11:37:49 ERROR]: Could not pass event PlayerChangePlotEvent to Towny v0.93.0.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-f6a273b-db10914]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-f6a273b-db10914]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-f6a273b-db10914]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-f6a273b-db10914]
at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerMoveChunk(TownyPlayerListener.java:966) ~[?:?]
at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerMove(TownyPlayerListener.java:660) ~[?:?]
at sun.reflect.GeneratedMethodAccessor175.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-f6a273b-db10914]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-f6a273b-db10914]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-f6a273b-db10914]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:946) ~[server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-f6a273b-db10914]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [server.jar:git-Spigot-f6a273b-db10914]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
at com.palmergames.bukkit.towny.huds.PermHUD.updatePerms(PermHUD.java:61) ~[?:?]
at com.palmergames.bukkit.towny.huds.HUDManager.onPlayerMovePlotsEvent(HUDManager.java:93) ~[?:?]
at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-f6a273b-db10914]
... 24 more
```

**Comment by LlmDl** [comment]
Skipped form
