### ISSUE TITLE
ERROR Could not pass event PlayerFishEvent to Towny v0.93.0.0

### ISSUE THREAD

**Issue by Xenthyk** [TownyAdvanced/Towny#3194]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. When a player not in the town tries to fish another player the console throws the error 
[Sat, 2. Mar 2019 06:17:09 UTC ERROR] Could not pass event PlayerFishEvent to Towny v0.93.0.0
2.This can also happen if a player in the town is in a plot they dont have permission to build/destroy in the plot. 
3. If a player spams fishing on a player it has crashed me as a * permission user. Non * permission users are not affected. 

### What is the expected output?
1. The player should be allowed to fish another player if pvp is on regardless of build/destroy permissions. It may be linked to one or the other but I can test this more tomorrow.

### What is your Towny version?
Towny v0.93.0.0

### What is your spigot/craftbukkit version?
1.13.2 (Paper v543)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
     https://pastebin.com/e4Kqu7xa
2. Your Towny config.yml (if using MySQL please remove password,) :
     https://pastebin.com/9pLGcLYw
3. Your townyperms.yml :
     https://pastebin.com/gVm4L2tJ
4. Your log's error : 
     ERROR Could not pass event PlayerFishEvent to Towny v0.93.0.0

Im heading to bed but just ran into this problem. I plan on doing some more testing on this tomorrow so I can isolate if it's in anyway tied to another plugin (potentially mcmmo) and Ill update ticket with the logs/configs. Ill also see if I can reproduce it on my dev server when I have people to help.

**Comment by Xenthyk** [comment]
I have updated the links with my info above. I did some more testing today and it's connected to the Destroy permission in town. If I disable the ability to destroy for a player and they try to fish another player in that town. I havent tested if they fish a player not in that town would cause issues but this should be something you can easily reproduce. I removed mcmmo so that's not a factor.

**Comment by LlmDl** [comment]
I'll look into it, you might want to see about getting mythicmobs to not produce errors, as well as teh other plugins.

**Comment by Xenthyk** [comment]
Thanks! Turns out if someone spams this it lagged me out as a * permission to the point of needing to close my client and open it again. I'm not sure how that would happen when I didn't get any notifications and I wasn't the one being fished when this happened. 

As for the errors. Agreed. This is my dev server and I have a few people working on mythic mobs, quests, and trying out new plugins here before they are ready for live. I got logs from there just to eliminate plugins I thought might be conflicting from the main server and did extra testing there.

**Comment by LlmDl** [comment]
I dont see what you having * permission has anything to do with it though. Especially if you're not even the one being fished...

Am I not understanding correctly?

**Comment by Xenthyk** [comment]
I don't understand the connection there either. I'm just passing on all the information I found while testing. I tested this once when I wasn't even in the same world as the people fishing each other and another time right next to them. When the fishing pole is spammed it crashed my client both times. No one else was affected and I was the only one online with * permissions at the time. I was not opped either. 

Let me know if you want me to help test it out with you and Ill be more than happy to set up a time.

**Comment by LlmDl** [comment]
Are you hosting the server from the same PC or same network that you are playing on?

**Comment by Xenthyk** [comment]
No. Both servers are professionally hosted.

**Comment by LlmDl** [comment]
Shouldnt be an issue as of 0.93.1.0

**Comment by dextonanderson** [comment]
I believe this is still an issue:

```[09:44:50 ERROR]: Could not pass event PlayerFishEvent to Towny v0.93.0.0
java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerFishEvent.getHook()Lorg/bukkit/entity/Fish;
        at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerFishEvent(TownyPlayerListener.java:952) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor299.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at net.minecraft.server.v1_13_R2.EntityFishingHook.b(EntityFishingHook.java:428) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at net.minecraft.server.v1_13_R2.ItemFishingRod.a(ItemFishingRod.java:33) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at net.minecraft.server.v1_13_R2.ItemStack.a(ItemStack.java:336) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:419) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1401) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-fedcdc7e]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by LlmDl** [comment]
What towny version are you using @dextonanderson

**Comment by dextonanderson** [comment]
@LlmDl Towny version: 0.93.0.0

**Comment by dextonanderson** [comment]
I may have missed the update

**Comment by LlmDl** [comment]
Give this one a try Towny 0.93.1.0 PR4 ( https://cdn.discordapp.com/attachments/321710042091094026/597844593614258177/Towny.jar ) See changelog 0.93.0.1 and forward for changes: https://git.io/vxiWf @dextonanderson
