### ISSUE TITLE
Could not pass event PlayerTeleportEvent to Towny v0.93.0.0

### ISSUE THREAD

**Issue by Coarby** [TownyAdvanced/Towny#3236]
Hello, i have a problem.. 

> > [22:44:39 ERROR]: Could not pass event PlayerTeleportEvent to Towny v0.93.0.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:444) [server.jar:git-Spigot-db6de12-18fbb24]
at com.earth2me.essentials.paperlib.features.asyncteleport.AsyncTeleportSync.teleportAsync(AsyncTeleportSync.java:13) [EssentialsX-2.16.1.0.jar:?]
at com.earth2me.essentials.paperlib.environments.Environment.teleport(Environment.java:79) [EssentialsX-2.16.1.0.jar:?]
at com.earth2me.essentials.paperlib.PaperLib.teleportAsync(PaperLib.java:86) [EssentialsX-2.16.1.0.jar:?]
at com.earth2me.essentials.Teleport.now(Teleport.java:143) [EssentialsX-2.16.1.0.jar:?]
at com.earth2me.essentials.Teleport.teleport(Teleport.java:202) [EssentialsX-2.16.1.0.jar:?]
at com.earth2me.essentials.Teleport.teleportPlayer(Teleport.java:172) [EssentialsX-2.16.1.0.jar:?]
at com.earth2me.essentials.spawn.Commandspawn.respawn(Commandspawn.java:56) [EssentialsXSpawn-2.16.1.0.jar:?]
at com.earth2me.essentials.spawn.Commandspawn.run(Commandspawn.java:33) [EssentialsXSpawn-2.16.1.0.jar:?]
at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) [EssentialsX-2.16.1.0.jar:?]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:545) [EssentialsX-2.16.1.0.jar:?]
at com.earth2me.essentials.spawn.EssentialsSpawn.onCommand(EssentialsSpawn.java:64) [EssentialsXSpawn-2.16.1.0.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchFieldError: CHORUS_FRUIT
at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerTeleport(TownyPlayerListener.java:707) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]
... 31 more

Please help asap!

**Comment by LlmDl** [comment]
Skipped form, resubmit
