### ISSUE TITLE
TownyChat 0.54 isn't working so far

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#3277]
```
> [23:23:00] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to TownyChat v0.54
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[server.jar:git-Spigot-f8e1ae2-21dbe8a]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-f8e1ae2-21dbe8a]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [server.jar:git-Spigot-f8e1ae2-21dbe8a]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [server.jar:git-Spigot-f8e1ae2-21dbe8a]
at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [server.jar:git-Spigot-f8e1ae2-21dbe8a]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [server.jar:git-Spigot-f8e1ae2-21dbe8a]
at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [server.jar:git-Spigot-f8e1ae2-21dbe8a]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: AsyncChatHookEvent cannot be triggered asynchronously from another thread.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[server.jar:git-Spigot-f8e1ae2-21dbe8a]
at com.palmergames.bukkit.TownyChat.channels.StandardChannel.chatProcess(StandardChannel.java:127) ~[?:?]
at com.palmergames.bukkit.TownyChat.listener.TownyChatPlayerListener.onPlayerChat(TownyChatPlayerListener.java:169) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-f8e1ae2-21dbe8a]
... 11 more
```

**Comment by LlmDl** [comment]
rangewonk reports that he got this on 0.53:
```
[16:35:02] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to TownyChat v0.53
java.lang.IllegalStateException: AsyncChatHookEvent may only be triggered synchronously.
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:524) ~[patched_1.14.2.jar:git-Paper-65]
    at com.palmergames.bukkit.TownyChat.channels.StandardChannel.chatProcess(StandardChannel.java:127) ~[?:?]
    at com.palmergames.bukkit.TownyChat.listener.TownyChatPlayerListener.onPlayerChat(TownyChatPlayerListener.java:170) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor983.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-65]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.2.jar:git-Paper-65]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-65]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-65]
    at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1745) ~[patched_1.14.2.jar:git-Paper-65]
    at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1660) ~[patched_1.14.2.jar:git-Paper-65]
    at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.14.2.jar:git-Paper-65]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

He said that using the build of 0.54 with the above PR did not fix it.

**Comment by TheFlagCourier** [comment]
Cannot Replicate. Working fine on my end using both Towny and TownyChat master branches.
Env: Windows 10, OpenJDK 12, Paper 1.14.2 Build 66

Console Snippet: https://hastebin.com/tuxebosaje.md

**Comment by LlmDl** [comment]
I have since given the same build I gave rangewonk to someone else, they have not had any problems.

**Comment by ironchefpython** [comment]
Testing with Paper 1.14.2 Build 66 and https://github.com/TownyAdvanced/TownyChat@master I also get

    12.06 23:29:52 [Server] INFO java.lang.IllegalStateException: AsyncChatHookEvent may only be triggered asynchronously.
    12.06 23:29:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:522) ~[patched_1.14.2.jar:git-Paper-68]
    12.06 23:29:52 [Server] INFO at com.palmergames.bukkit.TownyChat.channels.StandardChannel.chatProcess(StandardChannel.java:126) ~[?:?]
    12.06 23:29:52 [Server] INFO at com.palmergames.bukkit.TownyChat.listener.TownyChatPlayerListener.onPlayerChat(TownyChatPlayerListener.java:133) ~[?:?]

**Comment by LlmDl** [comment]
@Articdive
