### ISSUE TITLE
Townychat enabling error

### ISSUE THREAD

**Issue by itsTurnip** [TownyAdvanced/Towny#3374]
### What steps will reproduce the problem?
1. Start server
2. Watch errors in console

### What is the expected output?
1. Correct plugin enabling

### What is your Towny version?
0.94.0.4

### What is your spigot/craftbukkit version?
1.13.2 final build
Server is running CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the [logs\latest.log](https://gist.github.com/itsTurnip/0353e7cdc196c48848d003a6ece4275f)
2. Your Towny [config.yml](https://gist.github.com/itsTurnip/9247308abe8afee09fa5c704869da18d) (if using MySQL please remove password,) :
3. Your [townyperms.yml](https://gist.github.com/itsTurnip/6be1eced8ef02e925f7419781baa09b7) :
4. Your log's error : 
```
java.lang.NullPointerException: null
        at com.palmergames.bukkit.TownyChat.Chat.registerObjectCommands(Chat.java:231) ~[?:?]
        at com.palmergames.bukkit.TownyChat.Chat.onEnable(Chat.java:84) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot.jar:git-Spigot-1a3504a-84f3da3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

(optional) If this is to do with permissions, 
5. Your permissions file : no

(optional) If this is to do with chat,
6. Your [chatconfig.yml](https://gist.github.com/itsTurnip/2f015656cbca680cc7830724a3b7a282)
7. Your [channels.yml](https://gist.github.com/itsTurnip/3fcd731b021556fc137ea0e7afafa9fd)

**Comment by LlmDl** [comment]
Put the commands back for the local and global channels in the channels.yml.

**Comment by itsTurnip** [comment]
> 
> 
> Put the commands back for the local and global channels in the channels.yml.

Thanks, but what are the defaults?

**Comment by LlmDl** [comment]
[g] [l,lc]

**Comment by LlmDl** [comment]
Also if you're not on 1.14 you shouldn't be using anything past 0.94.0.0. Might not cause issues but it might.

**Comment by itsTurnip** [comment]
> 
> 
> Also if you're not on 1.14 you shouldn't be using anything past 0.94.0.0. Might not cause issues but it might.

I found that new dynmap-towny works only with towny 0.94.0.2.

**Comment by LlmDl** [comment]
Yeah I remade it for the new towny api.

**Comment by itsTurnip** [comment]
> 
> 
> Yeah I remade it for the new towny api.

Usually i search for a latest version of plugin :)
Would older versions of dynmap-towny work fine with 0.94.0.0?

**Comment by LlmDl** [comment]
It should, 0.94.0.0 is pre-new-api.

**Comment by itsTurnip** [comment]
> 
> 
> It should, 0.94.0.0 is pre-new-api.

Hmh... Okay, i will try using 0.94.0.2 with hope no issues would be there 😃 
Will i get in trouble downgrading 0.94.0.2 to 0.94.0.0?

**Comment by LlmDl** [comment]
Stick with 0.94.0.4
