### ISSUE TITLE
DeluxeChat TownyChat Asyncronous Chat Event

### ISSUE THREAD

**Issue by TheRBZ** [TownyAdvanced/Towny#3377]
### What steps will reproduce the problem?
Step 1. Have TownyChat and DeluxeChat installed.
Step 2. Use /g <message> (or /tc and /nc).
Step 3. DeluxeChat's format isn't used (The one in ChatConfig.yml is) and throws an error.

### What is the expected output?
Step 1. Have TownyChat and DeluxeChat installed.
Step 2. Use /g <message> (or /tc and /nc).
Step 3. DeluxeChat's format is used and doesn't throw an error.

### What is your Towny version?
Towny: 0.94.0.5
TownyChat: 0.56

### What is your spigot/craftbukkit version?
Paper version git-Paper-167 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:
1. Log Startup: https://pastebin.com/E6amzmFW
2. Towny/settings/config.yml: https://pastebin.com/ZbFGCsQT
3. Towny/settings/townyperms.yml: https://pastebin.com/WDtBjmSw
4. Log Error: https://pastebin.com/u169ntzU

(optional) If this is to do with chat,
6. Towny/settings/ChatConfig.yml: https://pastebin.com/s5gPySmY
7. Towny/settings/Channels.yml: https://pastebin.com/i5JMGEx2

**Comment by LlmDl** [comment]
I've given @TheRBZ a test build to try out. Anyone else can give their feedback on if if they'd like:

https://cdn.discordapp.com/attachments/581163022874050569/613501379423502408/TownyChat.jar

Requires Towny 0.94.0.2+

**Comment by TheRBZ** [comment]
Issue still persists when using the commands (/g <message>, /tc <message>, /nc <message>)
`[07:35:09] [Server thread/INFO]: therbz issued server command: /g dwadaw
[07:35:09] [Server thread/ERROR]: Could not pass event AsyncChatHookEvent to DeluxeChat v1.14.4
java.lang.IllegalStateException: DeluxeChatEvent may only be triggered asynchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:531) ~[patched_1.14.4.jar:git-Paper-167]
	at me.clip.deluxechat.listeners.TownyChatListener.onChat(TownyChatListener.java:303) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor948.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-167]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
	at com.palmergames.bukkit.TownyChat.channels.StandardChannel.chatProcess(StandardChannel.java:127) ~[?:?]
	at com.palmergames.bukkit.TownyChat.listener.TownyChatPlayerListener.onPlayerChat(TownyChatPlayerListener.java:133) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1060.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-167]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1713) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.chat(CraftPlayer.java:453) ~[patched_1.14.4.jar:git-Paper-167]
	at com.palmergames.bukkit.TownyChat.Command.commandobjects.ChannelJoinAliasCommand.execute(ChannelJoinAliasCommand.java:106) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-167]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[07:35:09] [Server thread/INFO]: therbz » dwadaw`
and now something different happens, an error is thrown even if I use either of the commands (/g, /tc, /nc) to switch channels and THEN talk in chat.
`[07:35:46] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to TownyChat v0.56
java.lang.IllegalStateException: AsyncChatHookEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.4.jar:git-Paper-167]
	at com.palmergames.bukkit.TownyChat.channels.StandardChannel.chatProcess(StandardChannel.java:127) ~[?:?]
	at com.palmergames.bukkit.TownyChat.listener.TownyChatPlayerListener.onPlayerChat(TownyChatPlayerListener.java:153) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1060.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-167]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1713) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.14.4.jar:git-Paper-167]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[07:35:46] [Async Chat Thread - #0/INFO]: therbz » reee`

**Comment by LlmDl** [comment]
2nd Test build:
https://cdn.discordapp.com/attachments/581163022874050569/613697317417254922/TownyChat.jar

Reports that using /g, then saying your message on a different line works without error.

But speaking into a channel using /g {message on same line} is causing an error

```
[12:28:43] [Server thread/ERROR]: Could not pass event AsyncPlayerChatEvent to TownyChat v0.56
java.lang.IllegalStateException: AsyncChatHookEvent may only be triggered asynchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:531) ~[patched_1.14.4.jar:git-Paper-167]
	at com.palmergames.bukkit.TownyChat.channels.StandardChannel.chatProcess(StandardChannel.java:127) ~[?:?]
	at com.palmergames.bukkit.TownyChat.listener.TownyChatPlayerListener.onPlayerChat(TownyChatPlayerListener.java:133) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1060.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-167]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1713) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.chat(CraftPlayer.java:453) ~[patched_1.14.4.jar:git-Paper-167]
	at com.palmergames.bukkit.TownyChat.Command.commandobjects.ChannelJoinAliasCommand.execute(ChannelJoinAliasCommand.java:106) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-167]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[12:28:43] [Server thread/INFO]: TOWN | therbz » d
```

**Comment by LlmDl** [comment]
Just an update for anyone with this issue.

Seems like we cannot solve it on our end, if we force it to async we have errors, if we force it to not be async we have errors.

The original error in the OP is actually the DC townychatlistener complaining that DC doesn't allow things to be triggered asynch. Pretty sure they need to update their TownyChatListener to accommodate the changes they made in their 1.14 builds.
