### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by itzfunday** [TownyAdvanced/Towny#3381]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.typing /n list
2.or /t list
3.

### What is the expected output?
1.> [04:22:57 ERROR]: Unhandled exception executing command 't' in plugin Towny v0.93.1.0
org.bukkit.command.CommandException: Unhandled exception executing command 't' in plugin Towny v0.93.1.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:469) [EssentialsX-2.17.0.7.jar:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:458) [EssentialsX-2.17.0.7.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalAccessError: com/palmergames/bukkit/towny/command/TownCommand$4
at com.palmergames.bukkit.towny.command.TownCommand.listTowns(TownCommand.java:963) ~[?:?]
at com.palmergames.bukkit.towny.command.TownCommand.parseTownCommand(TownCommand.java:198) ~[?:?]
at com.palmergames.bukkit.towny.command.TownCommand.onCommand(TownCommand.java:120) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-dcd1643-e60fc34]
2.
3.

### What is your Towny version?
Do not say "latest".
0.93.1

### What is your spigot/craftbukkit version?
Do not say "latest".
1.12.2

**Comment by LlmDl** [comment]
Skipped form. Resubmit.
