### ISSUE TITLE
Exception when you delete Town

### ISSUE THREAD

**Issue by HotdogVanDriver** [TownyAdvanced/Towny#3398]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Use deletion command
2. Confirm town deletion
3. Exception thrown over and over again in console

### What is the expected output?
1. Town deletes normally
2.
3.

### What is your Towny version?
0.94.0.5

### What is your spigot/craftbukkit version?
Paper version git-Paper-135

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/YHyGfRsv

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/YuryB2GZ

3. Your townyperms.yml :
https://pastebin.com/180Sgtzt

4. Your log's error : 
https://pastebin.com/XmiiBk6K

(optional) If this is to do with permissions, 
5. Your permissions file :
N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml : N/A
7. Your channels.yml : N/A

**Comment by LlmDl** [comment]
The town that was deleted is having a hard time reverting the blocks back to their pre-claimed state.

Maybe the town was claimed on an older version of minecraft and towny?

**Comment by HotdogVanDriver** [comment]
I had only made the claim about 30 minutes prior. Didn't change the version minecraft or Towny in between. I only installed Towny today. 

Just checked my console and it's throwing a new exception literally every single second:
https://pastebin.com/ym7yhYPa

**Comment by LlmDl** [comment]
Stop the server and delete the towny\data\regen.txt file.

**Comment by winnipeg21** [comment]
Having the same issue, world regen is turned off. Config syntax is valid. Paperspigot 172

**Comment by LlmDl** [comment]
@winnipeg21 turned off in teh config or turned off in the world (use /tw toggle revertunclaim) the config is only for default settings.

**Comment by Momshroom** [comment]
Same issue:  Paper 176 (1.14.4), Towny 0.94.0.6.
The town in question is created, then I immediately do /ta newday... town correctly gets deleted but console starts spamming errors.

**Comment by Momshroom** [comment]
I can confirm that toggling revertunclaim off before the town is deleted prevents this from happening.

**Comment by LlmDl** [comment]
@Momshroom anything that would make this town's plot snapshots strange? Which version of Towny were they claimed with, was it pre 0.93.1.0?

**Comment by Momshroom** [comment]
No.  I claimed it immediately before the /ta newday command in 0.94.0.6.   I was testing your iConomy fix. (Ty for that!)

**Comment by LlmDl** [comment]
Can you tell from the log if the snapshot had finished being made?

**Comment by Momshroom** [comment]
I included the whole latest.log file.  Or did you mean the towny log?

**Comment by Momshroom** [comment]
Okay, after updating to 0.94.0.7, I toggled revertunclaim back on, made a new town, waited until the log said the plot snapshots were completed, and then caused the town to fall with /ta newday.  It still spams console with the errors:
[15:13:06 WARN]: [Towny] Task #27 for Towny v0.94.0.7 generated an exception
java.lang.NullPointerException: null
        at com.palmergames.bukkit.towny.object.TownBlock.getWorldCoord(TownBlock.java:357) ~[?:?]
        at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(PlotBlockData.java:99) ~[?:?]
        at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(RepeatingTimerTask.java:33) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-176]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-176]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[15:13:07 WARN]: [Towny] Task #27 for Towny v0.94.0.7 generated an exception
java.lang.NullPointerException: null
        at com.palmergames.bukkit.towny.object.TownBlock.getWorldCoord(TownBlock.java:357) ~[?:?]
        at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(PlotBlockData.java:99) ~[?:?]
        at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(RepeatingTimerTask.java:33) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-176]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-176]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by LlmDl** [comment]
Ok, tracked this down to a change I made to removing TownBlocks. I'd made the change to greatly reduce spam Exception messages when a town has many townblocks removed. Looks like the fix I made has the side effect of deleting the townblocks too early. Probably have to revert the whole mess and see if there's another better way to solve the exception spam.

**Comment by LlmDl** [comment]
This is not longer an issue as of 0.94.0.8, we are reverting the above fix.
