### ISSUE TITLE
Conquering townblocks

### ISSUE THREAD

**Issue by AngeloDaddi** [TownyAdvanced/Towny#3430]
### What steps will reproduce the problem?
1. Start the war
2. Let two nations be enemies
3. Let a player conquer a townblock

The result is that when the health of the townblock reaches 1, the chat will start to spam that the town got a point. Also, every war tick, the enemy town loses $100.

### What is the expected output?
1. The player conquers the enemy townblock;
2. the player's town get 10 points;
3. the enemy's town lose $100.

### What is your Towny version?
Do not say "latest". Towny-0.94.0.15

### What is your spigot/craftbukkit version?
Do not say "latest". Paper-175

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/npdhDMe3
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/S9y1Lpnt
3. Your townyperms.yml : https://pastebin.com/AWh8WDcZ
4. Your log's error : 

```
[13:31:11] [Craft Scheduler Thread - 10/INFO]: [com.palmergames.bukkit.towny] [Town Msg] Aalborg: La tua citt? ha perso ?100,00.
[13:31:11] [Craft Scheduler Thread - 10/INFO]: [com.palmergames.bukkit.towny] [Global Msg] [Guerra] Palermo ha ottenuto 1 punti per aver eliminato il lotto di citt? [Aalborg](255,-214)!
[13:31:11] [Craft Scheduler Thread - 10/WARN]: [Towny] Plugin Towny v0.94.0.15 generated an exception while executing task 856
java.lang.IllegalStateException: TownScoredEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.4.jar:git-Paper-175]
	at com.palmergames.bukkit.towny.war.eventwar.War.townScored(War.java:322) ~[?:?]
	at com.palmergames.bukkit.towny.war.eventwar.War.remove(War.java:537) ~[?:?]
	at com.palmergames.bukkit.towny.war.eventwar.War.attackPlot(War.java:457) ~[?:?]
	at com.palmergames.bukkit.towny.war.eventwar.War.updateWarZone(War.java:362) ~[?:?]
	at com.palmergames.bukkit.towny.war.eventwar.WarTimerTask.run(WarTimerTask.java:119) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-175]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-175]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[13:31:11] [Log4j2-TF-1-AsyncLogger[AsyncContext@8bcc55f]-1/INFO]: [Town Msg] Aalborg: La tua citt?? ha perso ???100,00.
[13:31:11] [Log4j2-TF-1-AsyncLogger[AsyncContext@8bcc55f]-1/INFO]: [Global Msg] [Guerra] Palermo ha ottenuto 1 punti per aver eliminato il lotto di citt?? [Aalborg](255,-214)!
[13:31:16] [Craft Scheduler Thread - 17/INFO]: [com.palmergames.bukkit.towny] [Town Msg] Aalborg: La tua citt? ha perso ?100,00.
[13:31:16] [Craft Scheduler Thread - 17/INFO]: [com.palmergames.bukkit.towny] [Global Msg] [Guerra] Palermo ha ottenuto 1 punti per aver eliminato il lotto di citt? [Aalborg](255,-214)!
[13:31:16] [Log4j2-TF-1-AsyncLogger[AsyncContext@8bcc55f]-1/INFO]: [Town Msg] Aalborg: La tua citt?? ha perso ???100,00.
[13:31:16] [Craft Scheduler Thread - 17/WARN]: [Towny] Plugin Towny v0.94.0.15 generated an exception while executing task 856
java.lang.IllegalStateException: TownScoredEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.4.jar:git-Paper-175]
	at com.palmergames.bukkit.towny.war.eventwar.War.townScored(War.java:322) ~[?:?]
	at com.palmergames.bukkit.towny.war.eventwar.War.remove(War.java:537) ~[?:?]
	at com.palmergames.bukkit.towny.war.eventwar.War.attackPlot(War.java:457) ~[?:?]
	at com.palmergames.bukkit.towny.war.eventwar.War.updateWarZone(War.java:362) ~[?:?]
	at com.palmergames.bukkit.towny.war.eventwar.WarTimerTask.run(WarTimerTask.java:119) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-175]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-175]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

(optional) If this is to do with permissions, 
5. Your permissions fil :

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
Fixed as of https://github.com/TownyAdvanced/Towny/commit/71b690dc4389e038ef09c269a7a3e5dcecd43d84 will be a part of 0.94.0.16.
