### ISSUE TITLE
Tax day generates an issue, brobably has to do with a town i tried to revive

### ISSUE THREAD

**Issue by TheodorAndrei4** [TownyAdvanced/Towny#3587]
### What steps will reproduce the problem?
1.wait for the towny upkeep so a town gets deleted
2.proceed to modify the towns config file and re-add the deleted town name back there
3.take out the town config from deleted folder and move it back to the towns folder

### What is the expected output?
1.profit
2.on the next upkeep, an error should pop up
3.

### What is your Towny version?
0.95.2.0

### What is your spigot/craftbukkit version?
[18:10:58 INFO]: This server is running Paper version git-Paper-26 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : [latest.log]https://github.com/TownyAdvanced/Towny/files/4007192/latest.log
2. Your Towny config.yml (if using MySQL please remove password,) : 
[config.txt](https://github.com/TownyAdvanced/Towny/files/4007196/config.txt)
3. Your townyperms.yml :
4. Your log's error : 
*bold*[Towny] Plugin Towny v0.95.2.0 generated an exception while executing task 54
java.lang.NullPointerException: null
        at com.palmergames.bukkit.towny.db.TownyDatabaseHandler.removeTown(TownyDatabaseHandler.java:614) ~[?:?]
        at com.palmergames.bukkit.towny.tasks.DailyTimerTask.collectTownCosts(DailyTimerTask.java:383) ~[?:?]
        at com.palmergames.bukkit.towny.tasks.DailyTimerTask.run(DailyTimerTask.java:58) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-26]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.1.jar:git-Paper-26]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.1.jar:git-Paper-26]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]*bold*
(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
[The error is specifically complaining that it cannot remove the town from the world.](https://github.com/TownyAdvanced/Towny/blob/0.95.2.0/src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java#L614)

This is because when you manually un-delete a town there are a lot of things that must be done other than just adding the file back to the towns folder. One of them is putting the town back into the towny\data\worlds\worldname.txt.

Not much to be done about this now anyways.
