### ISSUE TITLE
`PlayerChangePlotEvent` frequently causes NPEs

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#3923]
### What steps will reproduce the problem?
1. Enter a named plot

### What is the expected output?
1. No errors

### What is your Towny version?
`0.96.1.4` (also happened on `0.96.1.3`;  possibly earlier, but idr)

### What is your spigot/craftbukkit version?
`git-Paper-192 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

### Please link the following files:
1. Your full server startup from the logs\latest.log: https://pastebin.com/uSYhAi1w
2. Your Towny config.yml (if using MySQL please remove password): https://github.com/SettleScape/server/blob/master/plugins/Towny/settings/config.yml
3. Your townyperms.yml: https://github.com/SettleScape/server/blob/master/plugins/Towny/settings/townyperms.yml
4. Your log's error: `[Server thread/ERROR]: Could not pass event PlayerChangePlotEvent to Towny v0.96.1.4
java.lang.NullPointerException: null`

(optional) If this is to do with permissions, 
5. Your permissions file: https://github.com/SettleScape/server/tree/master/plugins/GroupManager

(optional) If this is to do with chat,
6. Your chatconfig.yml: https://github.com/SettleScape/server/blob/master/plugins/Towny/settings/ChatConfig.yml
7. Your channels.yml: https://github.com/SettleScape/server/blob/master/plugins/Towny/settings/Channels.yml

**Comment by LlmDl** [comment]
It has to be a named plot? One with no name doesn't NPE?

**Comment by MilesBHuff** [comment]
Just confirmed it in `0.96.1.5` as well.
Not sure;  I name all my plots.  Let me unname one and see.

**Comment by MilesBHuff** [comment]
Further investigation shows that it's not on every plot change.  I think if a specific plot change (ie, it might be relational (which plot to which plot) rather than specific to each plot) has already occurred, the error does not recur.
I will travel to a town I haven't yet visited today and see how it is there.

**Comment by MilesBHuff** [comment]
Spawning at the other town did not trigger an NPE.  Travelling 4 plots forward triggered 2 NPEs.
Tracing that 4-plot path 2 more times, once in each direction, resulted in 4 more NPEs, so 2 each.  So maybe it's not relational?
3/4 of these plots were unnamed.  One is the (Capitol).

**Comment by MilesBHuff** [comment]
Going between Capitol and Shop causes NPEs in this other town, but going between Shop and Reset does not cause NPEs.  
Going between two Shop plots, both named "Bazaar", causes NPEs.  I did the same experiment with another adjacent Shop/"Bazaar" plot, and also got NPEs.
Going between two Shop/"Bazaar" plots distant from the earlier ones also results in NPEs.
Yet again, going between Shop and Reset plots did not cause NPEs.

**Comment by MilesBHuff** [comment]
Going between two Wilds plots also causes NPEs.
Going in and out out town between Wilds and Wilderness does not cause NPEs.

**Comment by MilesBHuff** [comment]
I see a pattern, in that moving between like plots, when those plots have a specific plot type, causes NPEs.

**Comment by MilesBHuff** [comment]
I also got an NPE from this event when logging into a plot that wasn't inside a town -- bizarre!

**Comment by LlmDl** [comment]
How likely is it that these are old townblocks when your server was set to use 16 sized blocks?

**Comment by MilesBHuff** [comment]
A 0% chance -- there are only 5 or so mismatched town plots, and I haven't entered any of them.

**Comment by LlmDl** [comment]
So.... are you going to show us some of those townblock files or the full NPEs they make?

**Comment by MilesBHuff** [comment]
Only the first NPE per launch of the server provides a full stack trace.
I just woke up;  I'm going to delete the mismatched townblocks, restart my local server, and test.
I'll send you the stack trace I already have, first.

**Comment by MilesBHuff** [comment]
Here's the first NPE from the log I attached to my OP:
```
[05:10:46] [Server thread/ERROR]: Could not pass event PlayerChangePlotEvent to Towny v0.96.1.4
java.lang.NullPointerException: null
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[?:1.8.0_242]
	at java.util.regex.Matcher.reset(Matcher.java:309) ~[?:1.8.0_242]
	at java.util.regex.Matcher.<init>(Matcher.java:229) ~[?:1.8.0_242]
	at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[?:1.8.0_242]
	at net.md_5.bungee.api.chat.TextComponent.fromLegacyText(TextComponent.java:50) ~[patched_1.15.2.jar:git-Paper-192]
	at net.md_5.bungee.api.chat.TextComponent.fromLegacyText(TextComponent.java:32) ~[patched_1.15.2.jar:git-Paper-192]
	at com.palmergames.bukkit.towny.listeners.TownyCustomListener.onPlayerChangePlotEvent(TownyCustomListener.java:109) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor361.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-192]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-192]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-192]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-192]
	at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerMoveChunk(TownyPlayerListener.java:871) ~[?:?]
	at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerMove(TownyPlayerListener.java:588) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor374.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-192]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-192]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-192]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-192]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1115) ~[patched_1.15.2.jar:git-Paper-192]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-192]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.15.2.jar:git-Paper-192]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-192]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-192]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-192]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-192]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-192]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1089) ~[patched_1.15.2.jar:git-Paper-192]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1082) ~[patched_1.15.2.jar:git-Paper-192]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-192]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1156) ~[patched_1.15.2.jar:git-Paper-192]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Paper-192]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by LlmDl** [comment]
Ok so this was a bit of a mess in our code that I have fixed. But that said you have:
```
  # This setting only applies to servers running spigot, paper or bungeecord.
  # On servers using craftbukkit.jar the notifications will always appear in the chat.
  # When set to false the notifications will appear in the chat rather than the action bar.
  notifications_appear_in_action_bar: 'true'
  # This settings set the duration the actionbar (The text above the inventory bar) lasts in seconds
  notification_actionbar_duration: '1'
```

The reason you managed to get an error was your actionbar_duration is less than 3. The actionbar will appear for 3 seconds and no less, but we have code to make it last longer.

So you can set that to 4, and you won't have any issues until 0.96.1.6 is released and then you can have it set to 3. Setting it to less than 3 will have no effect.

**Comment by MilesBHuff** [comment]
Awesome -- thank you, LlmDl!
