### ISSUE TITLE
What's wrong with the plugin

### ISSUE THREAD

**Issue by dinidusam** [TownyAdvanced/Towny#4194]
[12:11:54 INFO]: [Towny] Enabling Towny v0.96.2.0
[12:11:54 INFO]: [Core] Checking update for Core v0.2.4[Core] Checking update for Bank v4.1.2-BETA[Core] Unable to check update for Bank v4.1.2-BETA[Core] Attempting to load default ItemUtils[Core] Loaded default, enjoy :)====================      Towny      ========================
[12:11:55 ERROR]: Error occurred while enabling Towny v0.96.2.0 (Is it up to date?)
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
        at com.palmergames.bukkit.towny.TownySettings.loadTownLevelConfig(TownySettings.java:124) ~[?:?]
        at com.palmergames.bukkit.towny.TownySettings.loadCachedObjects(TownySettings.java:261) ~[?:?]
        at com.palmergames.bukkit.towny.TownySettings.loadConfig(TownySettings.java:236) ~[?:?]
        at com.palmergames.bukkit.towny.TownyUniverse.loadSettings(TownyUniverse.java:75) ~[?:?]
        at com.palmergames.bukkit.towny.Towny.load(Towny.java:248) ~[?:?]
        at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:144) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-92]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-92]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-92]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-92]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-92]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12:11:55 INFO]: [Towny] Disabling Towny v0.96.2.0
[12:11:55 INFO]: ==============================================================
[12:11:55 INFO]: [Towny] Version: 0.96.2.0 - Mod Disabled
[12:11:55 INFO]: =============================================================
[12:11:55 INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.18.0.0
[12:11:55 INFO]: [EssentialsSpawn] Starting Metrics. Opt-out using the global bStats config.
[12:11:55 INFO]: [TownyChat] Enabling TownyChat v0.72
[12:11:55 ERROR]: Error occurred while enabling TownyChat v0.72 (Is it up to date?)
java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/Towny
        at com.palmergames.bukkit.TownyChat.Chat.checkPlugins(Chat.java:117) ~[?:?]
        at com.palmergames.bukkit.TownyChat.Chat.onEnable(Chat.java:58) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-92]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-92]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-92]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-92]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-92]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.towny.Towny
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-92]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        ... 12 more
[12:11:55 INFO]: [TownyChat] Disabling TownyChat v0.72
[12:11:55 INFO]: [TownyNameUpdater] Enabling TownyNameUpdater v4.0
[12:11:55 ERROR]: Error occurred while enabling TownyNameUpdater v4.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/palmergames/util/FileMgmt
        at com.palmergames.townynameupdater.TownyNameUpdaterConfiguration.loadConfig(TownyNameUpdaterConfiguration.java:12) ~[?:?]
        at com.palmergames.townynameupdater.TownyNameUpdater.onEnable(TownyNameUpdater.java:20) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-92]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-92]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-92]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-92]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-92]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: com.palmergames.util.FileMgmt
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Paper-92]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-92]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        ... 12 more
[12:11:55 INFO]: [TownyNameUpdater] Disabling TownyNameUpdater v4.0

**Comment by LlmDl** [comment]
Your Town_level in the config.yml has a integer (ex: 1) when it should be a double (ex 1.0)
