### ISSUE TITLE
Question:Error with "dynmap-towny "

### ISSUE THREAD

**Issue by 1Vesemir1** [TownyAdvanced/Towny#4285]
I have connected dynmap to my server(it works fine) But when you try to put dynmap towny in the logs, an error appears -
[21:00:05 WARN]: [Dynmap-Towny] Plugin Dynmap-Towny v0.81 generated an exception while executing task 533
java.lang.NoSuchMethodError: com.palmergames.bukkit.towny.object.Town.getTownBlocks()Ljava/util/Collection;
at org.dynmap.towny.DynmapTownyPlugin.handleTown(DynmapTownyPlugin.java:632) ~[?:?]
at org.dynmap.towny.DynmapTownyPlugin.updateTowns(DynmapTownyPlugin.java:858) ~[?:?]
at org.dynmap.towny.DynmapTownyPlugin.access$000(DynmapTownyPlugin.java:55) ~[?:?]
at org.dynmap.towny.DynmapTownyPlugin$TownyUpdate.run(DynmapTownyPlugin.java:307) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-138]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-138]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-138]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

--------------------------------------------
Version towny -0.96.2.0
Version of dynmap towny - 0.81
Paper Core
The version of the server - 1.16.1

**Comment by LlmDl** [comment]
You didn't pay attention to the required towny version. Go back to dynmap-towny 0.80
