### ISSUE TITLE
NoSuchFieldError for Respawn Anchors on 1.15.2

### ISSUE THREAD

**Issue by ComradeVist** [TownyAdvanced/Towny#4444]
### What steps will reproduce the problem?
1. Create a server with version below 1.16
2. Click on anything

### What is the expected output?
1. Errors for 1.16 blocks should not occur on 1.15 servers

### What is your Towny version?
Towny 0.96.3.5

### What is your spigot/craftbukkit version?
Paper 390 (1.15.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/7qmcpjRw

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/mDrWhhSA (default)

3. Your townyperms.yml :
https://pastebin.com/tcphY020 (default)

4. Your log's error : 
```
[01:06:31] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Towny v0.96.3.5
java.lang.NoSuchFieldError: RESPAWN_ANCHOR
	at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerBlowsUpBedOrRespawnAnchor(TownyPlayerListener.java:371) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor37.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-390]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-390]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-390]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-390]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471) ~[patched_1.15.2.jar:git-Paper-390]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:438) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:143) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1365) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060) ~[patched_1.15.2.jar:git-Paper-390]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-Paper-390]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

**Comment by coopyo** [comment]
@LlmDl I am experiencing the same error on 1.14 with regard to HONEYCOMB blocks, which were added in 1.15.

If the patch was a quick if statement or catch block , I can fix that myself in the source code. I can also create a separate bug thread too. Just let me know the best course of action. 

Thanks,
Nick

**Comment by LlmDl** [comment]
@coopyo make a separate ticket and don't skip the form.
