### ISSUE TITLE
Cannons plugin explosions stopped working on Towny chunks

### ISSUE THREAD

**Issue by Darutan92** [TownyAdvanced/Towny#4776]
The explosions from the [Cannons](https://www.spigotmc.org/resources/cannons.56764/) shells stopped working in the Towny territory, this is not because of the on / off switch for explosions, but the following error is written to the console when it explodes:

_[ERROR] .... Could not pass event EntityExplodeEvent to Towny v0.96.7.0
[ERROR] .... Suspected Plugins:
[ERROR] .... Towny{enabled,ver=0.96.7.0,path=plugins/Towny-0.96.7.0.jar}
[ERROR] .... Cannons{enabled,ver=2.5.8,path=plugins/Cannons.jar}
[ERROR] .... Exception details below:
java.lang.NullPointerException: null
at com.palmergames.bukkit.towny.listeners.TownyEntityListener.onEntityExplode(TownyEntityListener.java:707) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor482.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at at.pavlov.cannons.CreateExplosion.blockBreaker(CreateExplosion.java:207) ~[?:?]
at at.pavlov.cannons.CreateExplosion.detonate(CreateExplosion.java:805) ~[?:?]
at at.pavlov.cannons.projectile.ProjectileManager.detonateProjectile(ProjectileManager.java:116) ~[?:?]
at at.pavlov.cannons.listener.EntityListener.ProjectileHit(EntityListener.java:75) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor504.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at org.bukkit.event.Event.callEvent(Event.java:45) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1350) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at net.minecraft.server.v1_16_R3.EntityFireball.tick(EntityFireball.java:70) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:1328) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:931) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1450) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:398) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1295) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1016) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]_

I don't know if the problem is with the Canons or the Towny.

### What steps will reproduce the problem?
Install the plugins Cannons and Towny, fire a TNT projectile at the territory of Towny, see an error in the console and an explosion that did not work.

### What is your Towny version?
**0.96.7.0**

### What is your spigot/craftbukkit version?
**yatopia-1.16.5-yatoclip-b31**

**Comment by Goosius1** [comment]
- I saw something similar just a few days ago
- I found that an NPE occurred, and the explosion did occur.
- I found a code issue which needed fixing, and fixed it on the Cannons side.
- Cannons merged the fix yesterday
- More info here:  https://github.com/DerPavlov/Cannons/pull/37
- Maybe test that fix and see if it resolves your issue also ?

**Comment by Darutan92** [comment]
> * I saw something similar just a few days ago
> * I found that an NPE occurred, and the explosion did occur.
> * I found a code issue which needed fixing, and fixed it on the Cannons side.
> * Cannons merged the fix yesterday
> * More info here:  [DerPavlov/Cannons#37](https://github.com/DerPavlov/Cannons/pull/37)
> * Maybe test that fix and see if it resolves your issue also ?
Yes, it works, I confirm, thanks.
