### ISSUE TITLE
Issue with loading any version past 0.96.7.4

### ISSUE THREAD

**Issue by LeftTheNegotiator** [TownyAdvanced/Towny#4804]
I get this error when updating past this version:

[16:42:03 INFO]: [Towny] Lang: english.yml v0.1 loaded.
[16:42:03 INFO]: [Towny] Database: [Load] flatfile [Save] flatfile
[16:42:03 WARN]: com.palmergames.bukkit.towny.exceptions.InvalidNameException: Spawn is an invalid name.
[16:42:03 WARN]:        at com.palmergames.bukkit.util.NameValidation.checkAndFilterName(NameValidation.java:41)
[16:42:03 WARN]:        at com.palmergames.bukkit.towny.TownyUniverse.newTown(TownyUniverse.java:628)
[16:42:03 WARN]:        at com.palmergames.bukkit.towny.TownyUniverse.newTownInternal(TownyUniverse.java:611)
[16:42:03 WARN]:        at com.palmergames.bukkit.towny.db.TownyFlatFileSource.loadTownList(TownyFlatFileSource.java:257)
[16:42:03 WARN]:        at com.palmergames.bukkit.towny.db.TownyDataSource.loadAll(TownyDataSource.java:55)
[16:42:03 WARN]:        at com.palmergames.bukkit.towny.TownyUniverse.loadDatabase(TownyUniverse.java:256)
[16:42:03 WARN]:        at com.palmergames.bukkit.towny.TownyUniverse.loadAndSaveDatabase(TownyUniverse.java:214)
[16:42:03 WARN]:        at com.palmergames.bukkit.towny.TownyUniverse.loadSettings(TownyUniverse.java:129)
[16:42:03 WARN]:        at com.palmergames.bukkit.towny.Towny.load(Towny.java:256)
[16:42:03 WARN]:        at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:149)
[16:42:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:42:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[16:42:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[16:42:03 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[16:42:03 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[16:42:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468)
[16:42:03 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:249)
[16:42:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:947)
[16:42:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[16:42:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

Towny locks into safe mode and I have no idea why it does.

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/commit/2b75140fe1e8c2ce4dd28114ce37dcbc7d066d2d fixes this
