### ISSUE TITLE
TownyChat doesnt seem to load.

### ISSUE THREAD

**Issue by BerryStraww** [TownyAdvanced/Towny#4817]
I know this issue has been posted before, but i still cant figure out what was wrong, im not that good at these things
could someone help me? im using spigot btw

[23:00:43 ERROR]: Could not pass event AsyncPlayerChatEvent to TownyChat v0.87
java.util.UnknownFormatConversionException: Conversion = '{'
        at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:101) ~[patched_1.16.4.jar:git-Paper-416]
        at com.palmergames.bukkit.TownyChat.channels.StandardChannel.chatProcess(StandardChannel.java:135) ~[?:?]
        at com.palmergames.bukkit.TownyChat.listener.TownyChatPlayerListener.onPlayerChat(TownyChatPlayerListener.java:158) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor346.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-416]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:1934) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1849) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1787) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.4.jar:git-Paper-416]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by LlmDl** [comment]
Skipped the form.
