### ISSUE TITLE
Server random safemode after restart

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/Towny#5049]
### What steps will reproduce the problem?
Start Server

### What is the expected output?
No safe mode

### What is your Towny version?
Towny-0.97.0.0.jar

### What is your spigot/craftbukkit version?
Tuinity version git-Tuinity-"9f3435b" (MC: 1.16.5)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log :
https://pastebin.com/GQPnBxmJ
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/26PHgCqC
3. Your townyperms.yml :
https://pastebin.com/NihNUKyx
4. Your log's error : 
https://pastebin.com/u9avEatG

**Comment by ElMoha943** [comment]
I might add that the error is "msg_err_loading_group_list_at_line" but it wasnt in my english.yml

**Comment by LlmDl** [comment]
That safemode error says you have a duplicate plotgroup. What do the other safemode errors you've gotten look like?

**Comment by ElMoha943** [comment]
> That safemode error says you have a duplicate plotgroup. What do the other safemode errors you've gotten look like?

they all said the same, and i deleted the `data/plotgroups/4c78927f-c922-4c46-9b00-c3a8c8bbb2fe.data` but the error still happens.

**Comment by LlmDl** [comment]
What you have selected on the left side doesn't match what is listed in the error on the right side.

**Comment by ElMoha943** [comment]
> What you have selected on the left side doesn't match what is listed in the error on the right side.

ikr, i already deleted the one

**Comment by ElMoha943** [comment]
Well i had to delete all plotgroup data in order to fix it, but i would like to know why it happend.

**Comment by LlmDl** [comment]
No one's ever shown this to me before. Did you restore the towny data folder from a backup and merge the files into the existing data folder?

**Comment by ElMoha943** [comment]
> No one's ever shown this to me before. Did you restore the towny data folder from a backup and merge the files into the existing data folder?

No i just erased everything and set up the plot groups again, im in a test server so it wasnt a big of a deal. I also updated to the newest pre-release just in case...

**Comment by ElMoha943** [comment]
Well i now have some other errors in console:
```
[22:04:37 WARN]: [Towny] "Towny v0.97.0.9" has registered a listener for com.palmergames.bukkit.towny.war.flagwar.events.CellDefendedEvent on method "public void com.palmergames.bukkit.towny.war.flagwar.listeners.FlagWarCustomListener.onCellDefendedEvent(com.palmergames.bukkit.towny.war.flagwar.events.CellDefendedEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Shade, Modified by FuzzeWuzze. Forked by ElgarL. Forked by LlmDl.].
[22:04:37 WARN]: [Towny] "Towny v0.97.0.9" has registered a listener for com.palmergames.bukkit.towny.war.flagwar.events.CellAttackCanceledEvent on method "public void com.palmergames.bukkit.towny.war.flagwar.listeners.FlagWarCustomListener.onCellAttackCanceledEvent(com.palmergames.bukkit.towny.war.flagwar.events.CellAttackCanceledEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Shade, Modified by FuzzeWuzze. Forked by ElgarL. Forked by LlmDl.].
[22:04:37 WARN]: [Towny] "Towny v0.97.0.9" has registered a listener for com.palmergames.bukkit.towny.war.flagwar.events.CellWonEvent on method "public void com.palmergames.bukkit.towny.war.flagwar.listeners.FlagWarCustomListener.onCellWonEvent(com.palmergames.bukkit.towny.war.flagwar.events.CellWonEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Shade, Modified by FuzzeWuzze. Forked by ElgarL. Forked by LlmDl.].
[22:04:37 WARN]: [Towny] "Towny v0.97.0.9" has registered a listener for com.palmergames.bukkit.towny.war.flagwar.events.CellAttackEvent on method "public void com.palmergames.bukkit.towny.war.flagwar.listeners.FlagWarCustomListener.onCellAttackEvent(com.palmergames.bukkit.towny.war.flagwar.events.CellAttackEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Shade, Modified by FuzzeWuzze. Forked by ElgarL. Forked by LlmDl.].
```

```
[22:04:39 WARN]: [Towny] Task #73 for Towny v0.97.0.9 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.MemorySection.getKeys(boolean)" because the return value of "com.palmergames.bukkit.config.CommentedConfiguration.get(String)" is null
        at com.palmergames.bukkit.towny.permissions.TownyPerms.getNationRanks(TownyPerms.java:426) ~[?:?]
        at com.palmergames.bukkit.towny.permissions.TownyPerms$1.run(TownyPerms.java:332) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1080) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by LlmDl** [comment]
The first one is because you commented all your nation ranks out in teh townyperms.yml, you need to have one rank even if it has no nodes.

The second one is harmless, just Towny warning Towny there's deprecated listeners loading in Towny.

**Comment by ElMoha943** [comment]
I see, also i believe i know what may have caused the other error. For plot groups i used this format: `Ignis1,1 - Aqua1,2` and i believe the `,` are causing errors in the config.

**Comment by LlmDl** [comment]
Yes that would do that, I am going to prevent commas being used starting in the next pre-release.
