### ISSUE TITLE
JDBC Driver is deprecated

### ISSUE THREAD

**Issue by xSehrMotiviert** [TownyAdvanced/Towny#5203]
I just wanted to send you this. If this is already known, then please let me know. Thanks. :D

[20:57:45] [Server thread/WARN]: [Towny] Loaded class org.h2.Driver from Craftconomy3 v3.3.1-d99cf63-trv200 which is not a depend, softdepend or loadbefore of this plugin.
[20:57:45] [Server thread/WARN]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is$[20:57:45] [Server thread/WARN]: java.lang.NullPointerException
[20:57:45] [Server thread/WARN]:        at com.palmergames.bukkit.towny.object.Resident.setJailCell(Resident.java:132)
[20:57:45] [Server thread/WARN]:        at com.palmergames.bukkit.towny.db.TownySQLSource.loadResident(TownySQLSource.java:808)
[20:57:45] [Server thread/WARN]:        at com.palmergames.bukkit.towny.db.TownySQLSource.loadResidents(TownySQLSource.java:713)
[20:57:45] [Server thread/WARN]:        at com.palmergames.bukkit.towny.db.TownyDataSource.loadAll(TownyDataSource.java:56)
[20:57:45] [Server thread/WARN]:        at com.palmergames.bukkit.towny.TownyUniverse.loadDatabase(TownyUniverse.java:269)
[20:57:45] [Server thread/WARN]:        at com.palmergames.bukkit.towny.TownyUniverse.loadAndSaveDatabase(TownyUniverse.java:227)
[20:57:45] [Server thread/WARN]:        at com.palmergames.bukkit.towny.TownyUniverse.loadSettings(TownyUniverse.java:138)
[20:57:45] [Server thread/WARN]:        at com.palmergames.bukkit.towny.Towny.load(Towny.java:251)
[20:57:45] [Server thread/WARN]:        at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:140)
[20:57:45] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[20:57:45] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[20:57:45] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[20:57:45] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[20:57:45] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[20:57:45] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[20:57:45] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[20:57:45] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[20:57:45] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[20:57:45] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by LlmDl** [comment]
Closed with https://github.com/TownyAdvanced/Towny/commit/92c3afabbb0234c41880995e105103aafba4802e
