### ISSUE TITLE
Towny-0.97.3.0, TownyChat-0.91, TownyFlight-1.7.0

### ISSUE THREAD

**Issue by Chypik** [TownyAdvanced/Towny#5462]
decided to upgrade to the latest stable version

```
[05:31:56] [Server thread/INFO]: This server is running Paper version git-Paper-381 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: db0bff9)
[05:31:56] [Server thread/INFO]: Server Ping Player Sample Count: 6
[05:31:56] [Server thread/INFO]: Using 4 threads for Netty based IO
[05:31:56] [Server thread/INFO]: Default game type: SURVIVAL
[05:31:56] [Server thread/INFO]: Generating keypair
[05:31:56] [Server thread/INFO]: Starting Minecraft server on *:25565
[05:31:56] [Server thread/INFO]: Using epoll channel type
[05:31:56] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[05:31:56] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[05:31:56] [Server thread/WARN]: [io.netty.util.internal.MacAddressUtil] Failed to find a usable hardware address from the network interfaces; using random bytes: b3:79:dd:09:d8:68:da:84
[05:31:56] [Server thread/ERROR]: Could not load 'plugins/TownyChat-0.91.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[patched_1.17.1.jar:git-Paper-381]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:158) ~[patched_1.17.1.jar:git-Paper-381]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-381]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1587) ~[?:?]
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1354) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1450) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1263) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1225) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:706) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:240) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:171) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:348) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:319) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:285) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174) ~[patched_1.17.1.jar:git-Paper-381]
	... 6 more
[05:31:56] [Server thread/ERROR]: Could not load 'plugins/Towny-0.97.3.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[patched_1.17.1.jar:git-Paper-381]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:158) ~[patched_1.17.1.jar:git-Paper-381]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-381]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1587) ~[?:?]
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1354) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1450) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1263) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1225) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:706) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:240) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:171) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:348) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:319) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:285) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174) ~[patched_1.17.1.jar:git-Paper-381]
	... 6 more
[05:31:57] [Server thread/ERROR]: Could not load 'plugins/TownyFlight-1.7.0.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Towny]. Please download and install these plugins to run 'TownyFlight'.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:290) ~[patched_1.17.1.jar:git-Paper-381]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-381]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-381]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[05:31:57] [Server thread/ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
```

returned to the old version of the plugin
[Towny] Enabling Towny v0.97.0.23

**Comment by LlmDl** [comment]
Might be the jars got corrupted when you unzipped them. Re-download the .zip and re-upload the freshly unzipped jars to your server. No one else has this happening. Also, you'll have to update to TownyFlight 1.8.0 when you update your Towny.
