### ISSUE TITLE
Could not pass event PotionSplashEvent to Towny v0.97.5.11

### ISSUE THREAD

**Issue by Chypik** [TownyAdvanced/Towny#5638]
### What steps will reproduce the problem?

*

### What is the expected output?

*

### Towny version

[Towny]   Permissions: TownyPerms, LuckPerms 5.3.98 via Vault
[Towny]   Add-ons: TownyChat v0.93, TownyFlight v1.8.2, LuckPerm    v5.3.98
[Towny] Version: 0.97.5.11 - Plugin Enabled

### Server version

Paper-152 (MC: 1.18.1)

### Please use Pastebin.com to link the following files

```
[15:32:52] [Async Chat Thread - #7/INFO]: Ⓖ [0_0] Глава - [Legenda] calculator_o_c :  ./plot toggle pvp off
[15:33:02] [Server thread/ERROR]: Could not pass event PotionSplashEvent to Towny v0.97.5.11
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getLocation()" because "attackingEntity" is null
	at com.palmergames.bukkit.towny.utils.CombatUtil.preventDamageCall(CombatUtil.java:131) ~[towny-0.97.5.11.jar:?]
	at com.palmergames.bukkit.towny.utils.CombatUtil.preventDamageCall(CombatUtil.java:103) ~[towny-0.97.5.11.jar:?]
	at com.palmergames.bukkit.towny.listeners.TownyEntityListener.onPotionSplashEvent(TownyEntityListener.java:372) ~[towny-0.97.5.11.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor251.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-152]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:793) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.world.entity.projectile.ThrownPotion.applySplash(ThrownPotion.java:200) ~[?:?]
	at net.minecraft.world.entity.projectile.ThrownPotion.onHit(ThrownPotion.java:114) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:172) ~[?:?]
	at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:79) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-152]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:33:07] [Server thread/ERROR]: Could not pass event PotionSplashEvent to Towny v0.97.5.11
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getLocation()" because "attackingEntity" is null
	at com.palmergames.bukkit.towny.utils.CombatUtil.preventDamageCall(CombatUtil.java:131) ~[towny-0.97.5.11.jar:?]
	at com.palmergames.bukkit.towny.utils.CombatUtil.preventDamageCall(CombatUtil.java:103) ~[towny-0.97.5.11.jar:?]
	at com.palmergames.bukkit.towny.listeners.TownyEntityListener.onPotionSplashEvent(TownyEntityListener.java:372) ~[towny-0.97.5.11.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor251.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-152]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:793) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.world.entity.projectile.ThrownPotion.applySplash(ThrownPotion.java:200) ~[?:?]
	at net.minecraft.world.entity.projectile.ThrownPotion.onHit(ThrownPotion.java:114) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:172) ~[?:?]
	at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:79) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-152]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:33:13] [Server thread/ERROR]: Could not pass event PotionSplashEvent to Towny v0.97.5.11
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getLocation()" because "attackingEntity" is null
	at com.palmergames.bukkit.towny.utils.CombatUtil.preventDamageCall(CombatUtil.java:131) ~[towny-0.97.5.11.jar:?]
	at com.palmergames.bukkit.towny.utils.CombatUtil.preventDamageCall(CombatUtil.java:103) ~[towny-0.97.5.11.jar:?]
	at com.palmergames.bukkit.towny.listeners.TownyEntityListener.onPotionSplashEvent(TownyEntityListener.java:372) ~[towny-0.97.5.11.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor251.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-152]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:793) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.world.entity.projectile.ThrownPotion.applySplash(ThrownPotion.java:200) ~[?:?]
	at net.minecraft.world.entity.projectile.ThrownPotion.onHit(ThrownPotion.java:114) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:172) ~[?:?]
	at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:79) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-152]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-152]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LlmDl** [comment]
Steps to reproduce was skipped.
