### ISSUE TITLE
TownyChat issue

### ISSUE THREAD

**Issue by Coder-TheSid** [TownyAdvanced/Towny#5823]
### What steps will reproduce the problem?

Just download 0.96 version of TownyChat and dont touch to configs

### What is the expected output?

..

### Towny version

TownyChat: 0.96
Towny: 0.98.1.2

### Server version

Purpur 1.17.1

### Please use Pastebin.com to link the following files

[16:25:19 ERROR]: Could not pass event AsyncPlayerChatEvent to TownyChat v0.96
java.lang.NoSuchMethodError: 'boolean com.palmergames.bukkit.towny.Towny.is116Plus()'
        at com.palmergames.bukkit.TownyChat.TownyChatFormatter.hexIfCompatible(TownyChatFormatter.java:207) ~[TownyChat-0.96.jar:?]
        at com.palmergames.bukkit.TownyChat.TownyChatFormatter.getChatFormat(TownyChatFormatter.java:216) ~[TownyChat-0.96.jar:?]
        at com.palmergames.bukkit.TownyChat.channels.StandardChannel.chatProcess(StandardChannel.java:130) ~[TownyChat-0.96.jar:?]
        at com.palmergames.bukkit.TownyChat.listener.TownyChatPlayerListener.onPlayerChat(TownyChatPlayerListener.java:165) ~[TownyChat-0.96.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor945.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1428]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2261) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2172) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2138) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[app:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Warriorrrr** [comment]
This was fixed in https://github.com/TownyAdvanced/Towny/commit/5781b577677031ed64d276244c99f21e496cb413, you can use [this jar](https://cdn.discordapp.com/attachments/581163022874050569/955112520509710387/towny-0.98.1.3.jar) in the meantime.
