### ISSUE TITLE
Doublequotes in metadata are improperly escaped

### ISSUE THREAD

**Issue by NeumimTo** [TownyAdvanced/Towny#5843]
### What steps will reproduce the problem?

Have a metadata that will contains doublequote character
Add metadata to the town
Save the town object
Load the town object
exception is thrown

```
[09:52:35 WARN]: [Towny] Error loading metadata for towny object com.palmergames.bukkit.towny.object.Townasdklfj!
[09:52:35 WARN]: java.io.IOException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 65 path $[0][3]
[09:52:35 WARN]:        at Towny-0.98.1.0.jar//com.palmergames.bukkit.towny.object.metadata.DataFieldIO.convertToArray(DataFieldIO.java:70)
[09:52:35 WARN]:        at Towny-0.98.1.0.jar//com.palmergames.bukkit.towny.object.metadata.DataFieldIO.deserializeMetaToRaw(DataFieldIO.java:75)
[09:52:35 WARN]:        at Towny-0.98.1.0.jar//com.palmergames.bukkit.towny.object.metadata.DataFieldIO.deserializeMeta(DataFieldIO.java:54)
[09:52:35 WARN]:        at Towny-0.98.1.0.jar//com.palmergames.bukkit.towny.object.metadata.MetadataLoader.initialDeserialization(MetadataLoader.java:68)
[09:52:35 WARN]:        at Towny-0.98.1.0.jar//com.palmergames.bukkit.towny.object.metadata.MetadataLoader.deserializeMetadata(MetadataLoader.java:55)
[09:52:35 WARN]:        at Towny-0.98.1.0.jar//com.palmergames.bukkit.towny.db.TownyFlatFileSource.loadTown(TownyFlatFileSource.java:924)
[09:52:35 WARN]:        at Towny-0.98.1.0.jar//com.palmergames.bukkit.towny.db.TownyDataSource.loadTowns(TownyDataSource.java:188)
[09:52:35 WARN]:        at Towny-0.98.1.0.jar//com.palmergames.bukkit.towny.db.TownyDataSource.loadAll(TownyDataSource.java:56)
[09:52:35 WARN]:        at Towny-0.98.1.0.jar//com.palmergames.bukkit.towny.TownyUniverse.loadDatabase(TownyUniverse.java:186)
[09:52:35 WARN]:        at Towny-0.98.1.0.jar//com.palmergames.bukkit.towny.TownyUniverse.loadAndSaveDatabase(TownyUniverse.java:142)
[09:52:35 WARN]:        at Towny-0.98.1.0.jar//com.palmergames.bukkit.towny.Towny.loadFoundation(Towny.java:262)
[09:52:35 WARN]:        at Towny-0.98.1.0.jar//com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:157)
[09:52:35 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:52:35 WARN]:
```

you can test it here https://github.com/NeumimTo/TownyColonies
build with gradle shadowJar task and ingame you do /townycolonies command and buy yourself a blueprint

This is how the saved data are escaped once loaded into java string object
```
new JsonParser().parse("[[\"TownyColonies-Structure\",\"townycolonies-town-structures\",\"\"\"\"]]")
```
This is how they should look like for the json parser to be able to parse the array
```
new JsonParser().parse("[[\"TownyColonies-Structure\",\"townycolonies-town-structures\",\"\\\"\\\"\"]]")
```

Metadata class: 
https://github.com/NeumimTo/TownyColonies/blob/master/src/main/java/cz/neumimto/towny/townycolonies/StructureMetadata.java

I attempted to fix the issue on my end by escaping value manually 
```
    public String serializeValueToString() {
        return gson.toJson(getValue()).replaceAll("\"","\\\\\"");
    }
```

While it works, it also works only for the first time the town is saved.
Im not sure why or how is this happening but the way im testing is 
>save metadata now properly escaped
>run /reload confirm few times
>for some reason towny wont call serializeValueToString and the metadata are saved again improperly escaped

### What is the expected output?

towny metadata should be able to hold jsons

### Towny version

0.98.1.0

### Server version

1.18.2

### Please use Pastebin.com to link the following files

error log see above

**Comment by LlmDl** [comment]
Not sure if this was a lack of the method not being overridden as I'd mentioned in the Discord, looks like you're using your own DB now.

**Comment by NeumimTo** [comment]
> Not sure if this was a lack of the method not being overridden as I'd mentioned in the Discord, looks like you're using your own DB now.

Well I solved it by switching to db. But the bug is still present. If anybody will try to store json in metadata they will run in the same issue.
