### ISSUE TITLE
This probably isnt a bug but just need help.

### ISSUE THREAD

**Issue by arizrain1** [TownyAdvanced/Towny#5846]
### What steps will reproduce the problem?

typing:  /town claim outpost

https://pastebin.com/eSUifqUe

### What is the expected output?
```
INFO Arizrain issued server command: /town claim outpost
03.04 18:00:35 [Server] ERROR null
03.04 18:00:35 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'town' in plugin Towny v0.98.1.0
03.04 18:00:35 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
03.04 18:00:35 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
03.04 18:00:35 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:908) ~[paper-1.18.1.jar:git-Paper-216]
03.04 18:00:35 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2289) ~[?:?]
03.04 18:00:35 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2100) ~[?:?]
03.04 18:00:35 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2081) ~[?:?]
03.04 18:00:35 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
03.04 18:00:35 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
03.04 18:00:35 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
03.04 18:00:35 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-216]
03.04 18:00:35 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
03.04 18:00:35 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
03.04 18:00:35 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1423) ~[paper-1.18.1.jar:git-Paper-216]
03.04 18:00:35 [Server] INFO at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-216]
03.04 18:00:35 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
03.04 18:00:35 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[paper-1.18.1.jar:git-Paper-216]
03.04 18:00:35 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[paper-1.18.1.jar:git-Paper-216]
03.04 18:00:35 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
03.04 18:00:35 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1371) ~[paper-1.18.1.jar:git-Paper-216]
03.04 18:00:35 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1277) ~[paper-1.18.1.jar:git-Paper-216]
03.04 18:00:35 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
03.04 18:00:35 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
03.04 18:00:35 [Server] INFO Caused by: java.lang.NoSuchMethodError: 'int ru.tehkode.permissions.PermissionGroup.getOptionInteger(java.lang.String, java.lang.String, int)'
03.04 18:00:35 [Server] INFO at net.milkbowl.vault.chat.plugins.Chat_PermissionsEx.getGroupInfoInteger(Chat_PermissionsEx.java:217) ~[Vault.jar:?]
03.04 18:00:35 [Server] INFO at net.milkbowl.vault.chat.Chat.getGroupInfoInteger(Chat.java:419) ~[Vault.jar:?]
03.04 18:00:35 [Server] INFO at com.palmergames.bukkit.towny.permissions.VaultPermSource.getGroupPermissionIntNode(VaultPermSource.java:90) ~[Towny-0.98.1.0.jar:?]
03.04 18:00:35 [Server] INFO at com.palmergames.bukkit.towny.TownySettings.getMaxResidentOutposts(TownySettings.java:2190) ~[Towny-0.98.1.0.jar:?]
03.04 18:00:35 [Server] INFO at com.palmergames.bukkit.towny.utils.OutpostUtil.OutpostTests(OutpostUtil.java:41) ~[Towny-0.98.1.0.jar:?]
03.04 18:00:35 [Server] INFO at com.palmergames.bukkit.towny.command.TownCommand.parseTownClaimCommand(TownCommand.java:3887) ~[Towny-0.98.1.0.jar:?]
03.04 18:00:35 [Server] INFO at com.palmergames.bukkit.towny.command.TownCommand.parseTownCommand(TownCommand.java:812) ~[Towny-0.98.1.0.jar:?]
03.04 18:00:35 [Server] INFO at com.palmergames.bukkit.towny.command.TownCommand.onCommand(TownCommand.java:533) ~[Towny-0.98.1.0.jar:?]
03.04 18:00:35 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
```
### Towny version

0.98.1.0  

### Server version

This server is running Paper version git-Paper-216 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 30cb7d0)
You are running the latest version
Previous version: git-Paper-85 (MC: 1.18.1)

### Please use Pastebin.com to link the following files

I just cannot read errors in console and was praying y'all could help me.  Thank you

**Comment by LlmDl** [comment]
Your permission plugin has caused an issue. You skipped the form.
