### ISSUE TITLE
Issues with safe mode and lang files

### ISSUE THREAD

**Issue by jman13378** [TownyAdvanced/Towny#6275]
### What steps will reproduce the problem?

jar and 
run the server

### What is the expected output?

to load towny normally without errors abt lang files or safe mode

### Towny version

latest

0.98.3.0

### Server version

Current: git-Purpur-1794 (MC: 1.19.2)*
Previous: git-Purpur-1605 (MC: 1.18.2)
* You are 41 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: [latest (1).log](https://github.com/TownyAdvanced/Towny/files/9906508/latest.1.log)
2. Your Towny config.yml: [config.txt](https://github.com/TownyAdvanced/Towny/files/9906233/config.txt)
3. Your townyperms.yml: [townyperms.txt](https://github.com/TownyAdvanced/Towny/files/9906234/townyperms.txt)
4. Your log's error: [latest (1).log](https://github.com/TownyAdvanced/Towny/files/9906520/latest.1.log)

**Comment by jman13378** [comment]
also the safemode error was abt errors loading 
Town1 them fixed it then wanted Town2

**Comment by LlmDl** [comment]
Retest using the latest pre-release: https://github.com/TownyAdvanced/Towny/releases/tag/0.98.3.18

**Comment by jman13378** [comment]
```
[16:17:26] [Server thread/INFO]: ================ [ExecutableItems] ================
[16:17:26] [Server thread/INFO]: [Towny] Enabling Towny v0.98.3.18
[16:17:26] [Server thread/INFO]: ====================      Towny      ========================
[16:17:26] [Server thread/INFO]: [Towny] Config: 0.98.3.3 applying 1 automatic update...
[16:17:26] [Server thread/INFO]: [Towny] Config: 0.98.3.4 applying 1 automatic update...
[16:17:26] [Server thread/INFO]: [Towny] Config: 0.98.3.13 applying 8 automatic updates...
[16:17:26] [Server thread/INFO]: [Towny] Successfully loaded translations for 37 languages.
[16:17:26] [Server thread/INFO]: [Towny] Config: Loaded 9 townblock types: default, bank, shop, wilds, inn, farm, embassy, arena, jail.
[16:17:26] [Server thread/INFO]: [Towny] Database: [Load] flatfile [Save] flatfile
[16:17:26] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading Server World List...
[16:17:26] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading World List...
[16:17:26] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading Nation list...
[16:17:26] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading Town list...
[16:17:26] [Server thread/WARN]: [Towny] Error: The town ��t��ken tried to load an invalid name, attempting to rename it to Town2.
[16:17:26] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading Group list...
[16:17:26] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading Jail List
[16:17:26] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading Resident list...
[16:17:26] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading TownBlock list...
[16:17:26] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Folders found 5
[16:17:26] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: World: towny_world_the_end loaded 0 TownBlocks.
[16:17:26] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because "this.world" is null
[16:17:26] [Server thread/WARN]: 	at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.object.WorldCoord.getWorldName(WorldCoord.java:61)
[16:17:26] [Server thread/WARN]: 	at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.object.WorldCoord.hashCode(WorldCoord.java:93)
[16:17:26] [Server thread/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
[16:17:26] [Server thread/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
[16:17:26] [Server thread/WARN]: 	at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.TownyUniverse.hasTownBlock(TownyUniverse.java:952)
[16:17:26] [Server thread/WARN]: 	at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.TownyUniverse.addTownBlock(TownyUniverse.java:941)
[16:17:26] [Server thread/WARN]: 	at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.db.TownyFlatFileSource.loadTownBlockList(TownyFlatFileSource.java:167)
[16:17:26] [Server thread/WARN]: 	at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.db.TownyDataSource.loadAll(TownyDataSource.java:58)
[16:17:26] [Server thread/WARN]: 	at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.TownyUniverse.loadDatabase(TownyUniverse.java:187)
[16:17:26] [Server thread/WARN]: 	at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.TownyUniverse.loadAndSaveDatabase(TownyUniverse.java:143)
[16:17:26] [Server thread/WARN]: 	at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.Towny.loadFoundation(Towny.java:266)
[16:17:26] [Server thread/WARN]: 	at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:159)
[16:17:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:17:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[16:17:26] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548)
[16:17:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596)
[16:17:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510)
[16:17:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[16:17:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427)
[16:17:26] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:343)
[16:17:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1116)
[16:17:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[16:17:26] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:17:26] [Server thread/ERROR]: [Towny] Database: Failed to load database.
com.palmergames.bukkit.towny.exceptions.initialization.TownyInitException: Database: Failed to load database.
	at com.palmergames.bukkit.towny.TownyUniverse.loadAndSaveDatabase(TownyUniverse.java:145) ~[towny-0.98.3.18.jar:?]
	at com.palmergames.bukkit.towny.Towny.loadFoundation(Towny.java:266) ~[towny-0.98.3.18.jar:?]
	at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:159) ~[towny-0.98.3.18.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1794]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:17:27] [Server thread/INFO]: =============================================================
[16:17:27] [Server thread/WARN]: [Towny] [WARNING] - ***** SAFE MODE ***** 0.98.3.18
[16:17:27] [Server thread/INFO
```

**Comment by LlmDl** [comment]
Did you change a world name?

**Comment by jman13378** [comment]
didn't touch any config files

**Comment by LlmDl** [comment]
The error says its loading a townblock that has a mis-matched world name. What folders are found in your towny\data\townblocks\ folder?

**Comment by jman13378** [comment]
![Screenshot_20221101-162321_Chrome.jpg](https://user-images.githubusercontent.com/101841938/199333637-151d6bdb-5d40-4a86-ba9f-f19685728d0d.jpg)

**Comment by LlmDl** [comment]
You have a folder from august that is called townyworld, do you have a world called townyworld in addition to the one called towny_world?

**Comment by jman13378** [comment]
just townyworld

**Comment by LlmDl** [comment]
So do any of those folders have names for which you do not have a matching world?

Did you perhaps change hosts and configure the wrong world name at some point?

**Comment by jman13378** [comment]
but all of those directories are old

**Comment by LlmDl** [comment]
Is that meant to be an answer to my questions?

**Comment by jman13378** [comment]
> So do any of those folders have names for which you do not have a matching world?
> 
> Did you perhaps change hosts and configure the wrong world name at some point?

![Screenshot_20221101-164801_Chrome.jpg](https://user-images.githubusercontent.com/101841938/199337894-b0091f0c-380e-4121-9588-ba57ca0fc61a.jpg)

and not that I know of

**Comment by LlmDl** [comment]
I dunno what to make of that. 

Your startup fails because a townblock is being loaded from a world your server doesn't have.

If you have a folder in your townblocks\ folder that isn't in your server you probably want to remove it.

**Comment by jman13378** [comment]
wut abt worlds.txt

**Comment by LlmDl** [comment]
I dont think we use that file any more.

**Comment by jman13378** [comment]
```
20:54:29] [Server thread/INFO]: [Towny] Enabling Towny v0.98.3.18
[20:54:29] [Server thread/INFO]: ====================      Towny      ========================
[20:54:29] [Server thread/INFO]: [Towny] Config: 0.98.3.3 applying 1 automatic update...
[20:54:29] [Server thread/INFO]: [Towny] Config: 0.98.3.4 applying 1 automatic update...
[20:54:29] [Server thread/INFO]: [Towny] Config: 0.98.3.13 applying 8 automatic updates...
[20:54:29] [Server thread/INFO]: [Towny] Successfully loaded translations for 37 languages.
[20:54:29] [Server thread/INFO]: [Towny] Config: Loaded 9 townblock types: default, bank, shop, wilds, inn, farm, embassy, arena, jail.
[20:54:29] [Server thread/INFO]: [Towny] Database: [Load] flatfile [Save] flatfile
[20:54:29] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading Server World List...
[20:54:29] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading World List...
[20:54:29] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading Nation list...
[20:54:29] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading Town list...
[20:54:29] [Server thread/WARN]: [Towny] Error: The town ��t��ken tried to load an invalid name, attempting to rename it to Town1.
[20:54:29] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading Group list...
[20:54:29] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading Jail List
[20:54:29] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading Resident list...
[20:54:29] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Loading TownBlock list...
[20:54:29] [Server thread/INFO]: [com.palmergames.bukkit.towny.debug] [Towny] Debug: Folders found 3
[20:54:29] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because "this.world" is null
[20:54:29] [Server thread/WARN]:     at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.object.WorldCoord.getWorldName(WorldCoord.java:61)
[20:54:29] [Server thread/WARN]:     at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.object.WorldCoord.hashCode(WorldCoord.java:93)
[20:54:29] [Server thread/WARN]:     at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
[20:54:29] [Server thread/WARN]:     at java.base/java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
[20:54:29] [Server thread/WARN]:     at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.TownyUniverse.hasTownBlock(TownyUniverse.java:952)
[20:54:29] [Server thread/WARN]:     at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.TownyUniverse.addTownBlock(TownyUniverse.java:941)
[20:54:29] [Server thread/WARN]:     at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.db.TownyFlatFileSource.loadTownBlockList(TownyFlatFileSource.java:167)
[20:54:29] [Server thread/WARN]:     at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.db.TownyDataSource.loadAll(TownyDataSource.java:58)
[20:54:29] [Server thread/WARN]:     at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.TownyUniverse.loadDatabase(TownyUniverse.java:187)
[20:54:29] [Server thread/WARN]:     at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.TownyUniverse.loadAndSaveDatabase(TownyUniverse.java:143)
[20:54:29] [Server thread/WARN]:     at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.Towny.loadFoundation(Towny.java:266)
[20:54:29] [Server thread/WARN]:     at towny-0.98.3.18.jar//com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:159)
[20:54:29] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:54:29] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[20:54:29] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548)
[20:54:29] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596)
[20:54:29] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510)
[20:54:29] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[20:54:29] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427)
[20:54:29] [Server thread/WARN]:     at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:343)
[20:54:29] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1116)
[20:54:29] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[20:54:29] [Server thread/WARN]:     at java.base/java.lang.Thread.run(Thread.java:833)
[20:54:29] [Server thread/ERROR]: [Towny] Database: Failed to load database.
com.palmergames.bukkit.towny.exceptions.initialization.TownyInitException: Database: Failed to load database.
    at com.palmergames.bukkit.towny.TownyUniverse.loadAndSaveDatabase(TownyUniverse.java:145) ~[towny-0.98.3.18.jar:?]
    at com.palmergames.bukkit.towny.Towny.loadFoundation(Towny.java:266) ~[towny-0.98.3.18.jar:?]
    at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:159) ~[towny-0.98.3.18.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596) ~[purpur-1.19.2.jar:git-Purpur-1794]
    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510) ~[purpur-1.19.2.jar:git-Purpur-1794]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1794]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1794]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1794]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1794]
    at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1794]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:54:29] [Server thread/INFO]: =============================================================
[20:54:29] [Server thread/WARN]: [Towny] [WARNING] - ***** SAFE MODE ***** 0.98.3.18
[20:54:29] [Server thread/INFO]: =============================================================
```

**Comment by LlmDl** [comment]
Its the same thing, make sure your townblocks\ folder's world names match what is on your server.

**Comment by jman13378** [comment]
they do

**Comment by jman13378** [comment]
nvm

**Comment by jman13378** [comment]
nvm they are all existent

**Comment by jman13378** [comment]
wb towny/data/worlds?

**Comment by LlmDl** [comment]
You can tell from teh debug messaging where its loading. Your world must not be loaded yet. Make your worlds load.

**Comment by jman13378** [comment]
how?

**Comment by jman13378** [comment]
like before towny

**Comment by LlmDl** [comment]
I dunno, I would talk to your host, assuming you're paying them money.

**Comment by jman13378** [comment]
I'm not my owner is

**Comment by jman13378** [comment]
but I'll ask

**Comment by LlmDl** [comment]
I get an email every time you reply by the way.

**Comment by jman13378** [comment]
![Screenshot_20221101-171702_Chrome.jpg](https://user-images.githubusercontent.com/101841938/199343383-caf7226e-0448-46f6-ab67-386bee6b5c03.jpg)

**Comment by jman13378** [comment]
it's a plugin.yml option

**Comment by LlmDl** [comment]
What plugin is loading your worlds? This isn't a Towny issue, your world loader is loading late. Your original startup full of errors shows a bunch of worlds loading after Towny.

**Comment by jman13378** [comment]
mv-core

**Comment by LlmDl** [comment]
Use mv-core to make the worlds load earlier.

**Comment by jman13378** [comment]
how i dont see an option for it

**Comment by jman13378** [comment]
Just so my answers clear all i did was edit the plugin.yml with [recaf](https://github.com/Col-E/Recaf) and added 
depend: Multiverse-Core

**Comment by LlmDl** [comment]
Towny has had Multiverse-Core in the plugin.yml for about 10 years already.

**Comment by jman13378** [comment]
> Towny has had Multiverse-Core in the plugin.yml for about 10 years already.

as a soft-depend though

**Comment by LlmDl** [comment]
We cannot ask every towny server to also install Multiverse-Core, so we cannot put it in as a Depend either.

**Comment by jman13378** [comment]
> We cannot ask every towny server to also install Multiverse-Core, so we cannot put it in as a Depend either.

I know
