### ISSUE TITLE
Bug when player tries to claim plot

### ISSUE THREAD

**Issue by ReverseR7** [TownyAdvanced/Towny#6475]
### What steps will reproduce the problem?

I set a plot in my town for sale with /plot fs and my players tries to claim it and i get this in my console

### What is the expected output?

That plot is claimed but he gets null error

### Towny version

0.98.6.4

### Server version

1.19.2

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:  https://pastebin.com/ZzD5bCLE
2. Your Towny config.yml: https://pastebin.com/G39mZAyD
3. Your townyperms.yml: https://pastebin.com/wWgHCRqm
4. Your log's error: (in latest.log)

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by LlmDl** [comment]
```
[02:04:46] [Server thread/INFO]: blockheadboy16 issued server command: /plot claim
[02:04:48] [Server thread/WARN]: [Towny] An exception occurred when initializing cached balance for an account (name: blockheadboy16), see the below error for more details.
[02:04:48] [Server thread/WARN]: java.lang.NullPointerException
[02:04:48] [Server thread/WARN]: 	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
[02:04:48] [Server thread/WARN]: 	at java.base/java.util.Optional.of(Optional.java:113)
[02:04:48] [Server thread/WARN]: 	at TNE-0.1.1.16.jar//net.tnemc.core.common.EconomyManager.getName(EconomyManager.java:105)
[02:04:48] [Server thread/WARN]: 	at TNE-0.1.1.16.jar//net.tnemc.core.common.api.IDFinder.getUsername(IDFinder.java:51)
[02:04:48] [Server thread/WARN]: 	at TNE-0.1.1.16.jar//net.tnemc.core.common.utils.MISCUtils.getPlayer(MISCUtils.java:80)
[02:04:48] [Server thread/WARN]: 	at TNE-0.1.1.16.jar//net.tnemc.core.common.currency.type.ItemType.getHoldings(ItemType.java:44)
[02:04:48] [Server thread/WARN]: 	at TNE-0.1.1.16.jar//net.tnemc.core.common.account.handlers.CoreHoldingsHandler.getHoldings(CoreHoldingsHandler.java:59)
[02:04:48] [Server thread/WARN]: 	at TNE-0.1.1.16.jar//net.tnemc.core.common.account.TNEAccount.getHoldings(TNEAccount.java:135)
[02:04:48] [Server thread/WARN]: 	at TNE-0.1.1.16.jar//net.tnemc.core.common.account.TNEAccount.getHoldings(TNEAccount.java:291)
[02:04:48] [Server thread/WARN]: 	at TNE-0.1.1.16.jar//net.tnemc.core.common.api.TNEAPI.getHoldings(TNEAPI.java:297)
[02:04:48] [Server thread/WARN]: 	at TNE-0.1.1.16.jar//net.tnemc.core.common.api.Economy_TheNewEconomy.getBalance(Economy_TheNewEconomy.java:104)
[02:04:48] [Server thread/WARN]: 	at TNE-0.1.1.16.jar//net.tnemc.core.common.api.Economy_TheNewEconomy.getBalance(Economy_TheNewEconomy.java:91)
[02:04:48] [Server thread/WARN]: 	at towny-0.98.6.4.jar//com.palmergames.bukkit.towny.object.economy.adapter.VaultEconomyAdapter.getBalance(VaultEconomyAdapter.java:33)
```

You can see above in the last line where we've used Vault to get to TheNewEconomy, which then fails and makes an NPE. You should be filing a ticket with TheNewEconomy.
