### ISSUE TITLE
towny error

### ISSUE THREAD

**Issue by haroldrc** [TownyAdvanced/Towny#6507]
### What steps will reproduce the problem?

1

### What is the expected output?

1

### Towny version

v0.98.6.8

### Server version

1.19.3

### Please use Pastebin.com to link the following files

[04:40:58 WARN]: [Towny] Plugin Towny v0.98.6.8 generated an exception while executing task 98
java.lang.NullPointerException: Cannot read field "update" because "query" is null
        at com.palmergames.bukkit.towny.db.TownySQLSource.lambda$new$0(TownySQLSource.java:169) ~[towny-0.98.6.8.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.19.3.jar:git-Pufferfish-58]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Warriorrrr** [comment]
You skipped the form (don't skip the form asking you to paste the required files). Query being null is also impossible since a new query object is created each time, so we can't find what's wrong without more info.
