### ISSUE TITLE
Towny v0.98.6.9 Exception while executing task 

### ISSUE THREAD

**Issue by TKwSni** [TownyAdvanced/Towny#6514]
### What steps will reproduce the problem?

1. Upgrade from v0.98.6.0 to v0.98.6.9
2. Start the server and wait

### What is the expected output?

Dont show any errors...

No idea what causes it, but just using the latest version from github shows a query error.

### Towny version

v0.98.6.9

### Server version

v1.19.3

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: https://pastebin.com/raw/7zr8E2XM
2. Your Towny config.yml: default file
3. Your townyperms.yml: default file
4. Your log's error:

```
[Towny] Plugin Towny v0.98.6.9 generated an exception while executing task 7
java.lang.NullPointerException: Cannot read field "update" because "query" is null
	at com.palmergames.bukkit.towny.db.TownySQLSource.lambda$new$0(TownySQLSource.java:169) ~[towny-0.98.6.9.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1921]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.3.jar:git-Purpur-1921]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	```

**Comment by LlmDl** [comment]
I could be useful to see your database.yml (with your password removed.)

We've had 2 occurrences of this so far. One person in discord said "wait i know, dw im just dumb 🍻" after they solved it themselves. The other person filed an [incomplete ticket.](https://github.com/TownyAdvanced/Towny/issues/6507#issuecomment-1445344537)

Hard to see how a query could be null when we're only every making new SQL_Tasks to put into the query queue.

**Comment by TKwSni** [comment]
```  
database:
  
  # Valid load and save types are: flatfile and mysql.
  database_load: mysql
  database_save: mysql
  
  # SQL database connection details (IF set to use mysql).
  sql:
    hostname: my.host.com
    port: '3306'
    dbname: dbname
    table_prefix: towny_
    username: username
    password: password
    flags: ?verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=utf-8
  
    # Modifiable settings to control the connection pooling.
    # Unless you actually know what you're doing and how Towny uses its mysql connection,
    # it is strongly recommended you do not change these settings.
    pooling:
      max_pool_size: '5'
      max_lifetime: '180000'
      connection_timeout: '5000'
  
  # The Database version number. Do not change.
  version: '1'
```

**Comment by LlmDl** [comment]
Nothing wrong there.

The error still makes no sense, the only way to get something into the queue is for it to be initialized, to have something null in the queue should be impossible.

**Comment by TKwSni** [comment]
what can I do to help you pinpoint this error, it gets like this after a while

```
[01:39:26 WARN]: [Towny] Plugin Towny v0.98.6.9 generated an exception while executing task 7
java.lang.NullPointerException: null
[01:40:37 WARN]: [Towny] Plugin Towny v0.98.6.9 generated an exception while executing task 7
java.lang.NullPointerException: null
[01:45:22 WARN]: [Towny] Plugin Towny v0.98.6.9 generated an exception while executing task 7
java.lang.NullPointerException: null
[01:46:36 WARN]: [Towny] Plugin Towny v0.98.6.9 generated an exception while executing task 7
java.lang.NullPointerException: null
[01:50:54 WARN]: [Towny] Plugin Towny v0.98.6.9 generated an exception while executing task 7
java.lang.NullPointerException: null
[01:52:49 WARN]: [Towny] Plugin Towny v0.98.6.9 generated an exception while executing task 7
java.lang.NullPointerException: null
[02:01:29 WARN]: [Towny] Plugin Towny v0.98.6.9 generated an exception while executing task 7
java.lang.NullPointerException: null

**Comment by LlmDl** [comment]
I don't believe I have any answers, it shouldn't be possible.

The other person who had solved it has not gotten back to me.
