### ISSUE TITLE
Error in Player Interact Event

### ISSUE THREAD

**Issue by madebygood** [TownyAdvanced/Towny#6868]
### What steps will reproduce the problem?

Starting from Towny 0.99.5.3, Bukkit displays error messages too fast.

I don't know when it happens, but it seems to happen in Interact.

### What is the expected output?

[14:21:27 ERROR]: Could not pass event PlayerInteractEvent to Towny v0.99.5.3
java.lang.NoSuchFieldError: BRUSH
        at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerInteract(TownyPlayerListener.java:395) ~[towny-0.99.5.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor924.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:528) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2051) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

![image](https://github.com/TownyAdvanced/Towny/assets/43653581/3268bbe0-9478-4007-8794-f49933293896)

### Towny version

0.99.5.3

### Server version

1.19.2 Purpur

### Please use Pastebin.com to link the following files

As a result of checking, it seems that the problem is not caused by my settings.

The settings remain the same,

This is a bug that occurred when I just upgraded the version to 0.9.55.2 => 0.9.55.3.

**Comment by madebygood** [comment]
https://github.com/TownyAdvanced/Towny/issues/6861#issue-1810841434

Maybe this makes issue?

**Comment by Warriorrrr** [comment]
Will be fixed by #6869, already reported in #6866

**Comment by Warriorrrr** [comment]
Actually already solved by f98ffb2e04f75d86d55600a7e248f578d2868176

**Comment by madebygood** [comment]
> Actually already solved by [f98ffb2](https://github.com/TownyAdvanced/Towny/commit/f98ffb2e04f75d86d55600a7e248f578d2868176)

0.99.5.4 version has been resolved.
But, 0.99.5.4 version problem is restart.

**Comment by LlmDl** [comment]
Are you using a 1.20 datapack or something on 1.19?
