### ISSUE TITLE
/towny claim problem - Folia

### ISSUE THREAD

**Issue by MrSugar08** [TownyAdvanced/Towny#7222]
### What steps will reproduce the problem?

1. /towny claim

### What is the expected output?

[14:28:45 ERROR]: Thread Folia Async Scheduler Thread Timer failed main thread c
heck: Cannot retrieve chunk asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71)
 ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockYAt(CraftWo
rld.java:995) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftRegionAccessor.getHighestBlockYA
t(CraftRegionAccessor.java:305) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockAt(CraftWor
ld.java:985) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at com.palmergames.bukkit.util.BlockUtil.getHighestNonLeafY(BlockUtil.ja
va:34) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.getParticleLocation(C
ellSurface.java:95) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.drawClaimingParticleO
nTopOfBlock(CellSurface.java:91) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.lambda$runClaimingPar
ticleOverSurfaceAtPlayer$0(CellSurface.java:44) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.scheduling.impl.FoliaTaskScheduler.lambd
a$runAsyncLater$10(FoliaTaskScheduler.java:110) ~[Towny.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncS
cheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:53
9) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:28:45 WARN]: [Towny] Async task for Towny v0.100.1.7 generated an exception
java.lang.IllegalStateException: Cannot retrieve chunk asynchronously
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72)
 ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockYAt(CraftWo
rld.java:995) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftRegionAccessor.getHighestBlockYA
t(CraftRegionAccessor.java:305) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockAt(CraftWor
ld.java:985) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at com.palmergames.bukkit.util.BlockUtil.getHighestNonLeafY(BlockUtil.ja
va:34) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.getParticleLocation(C
ellSurface.java:95) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.drawClaimingParticleO
nTopOfBlock(CellSurface.java:91) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.lambda$runClaimingPar
ticleOverSurfaceAtPlayer$0(CellSurface.java:44) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.scheduling.impl.FoliaTaskScheduler.lambd
a$runAsyncLater$10(FoliaTaskScheduler.java:110) ~[Towny.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncS
cheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:53
9) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:28:45 ERROR]: Thread Folia Async Scheduler Thread Timer failed main thread c
heck: Cannot retrieve chunk asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71)
 ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockYAt(CraftWo
rld.java:995) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftRegionAccessor.getHighestBlockYA
t(CraftRegionAccessor.java:305) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockAt(CraftWor
ld.java:985) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at com.palmergames.bukkit.util.BlockUtil.getHighestNonLeafY(BlockUtil.ja
va:34) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.getParticleLocation(C
ellSurface.java:95) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.drawClaimingParticleO
nTopOfBlock(CellSurface.java:91) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.lambda$runClaimingPar
ticleOverSurfaceAtPlayer$0(CellSurface.java:44) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.scheduling.impl.FoliaTaskScheduler.lambd
a$runAsyncLater$10(FoliaTaskScheduler.java:110) ~[Towny.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncS
cheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:53
9) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:28:45 WARN]: [Towny] Async task for Towny v0.100.1.7 generated an exception
java.lang.IllegalStateException: Cannot retrieve chunk asynchronously
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72)
 ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockYAt(CraftWo
rld.java:995) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftRegionAccessor.getHighestBlockYA
t(CraftRegionAccessor.java:305) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockAt(CraftWor
ld.java:985) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at com.palmergames.bukkit.util.BlockUtil.getHighestNonLeafY(BlockUtil.ja
va:34) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.getParticleLocation(C
ellSurface.java:95) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.drawClaimingParticleO
nTopOfBlock(CellSurface.java:91) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.lambda$runClaimingPar
ticleOverSurfaceAtPlayer$0(CellSurface.java:44) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.scheduling.impl.FoliaTaskScheduler.lambd
a$runAsyncLater$10(FoliaTaskScheduler.java:110) ~[Towny.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncS
cheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:53
9) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:28:45 ERROR]: Thread Folia Async Scheduler Thread Timer failed main thread c
heck: Cannot retrieve chunk asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71)
 ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockYAt(CraftWo
rld.java:995) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftRegionAccessor.getHighestBlockYA
t(CraftRegionAccessor.java:305) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockAt(CraftWor
ld.java:985) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at com.palmergames.bukkit.util.BlockUtil.getHighestNonLeafY(BlockUtil.ja
va:34) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.getParticleLocation(C
ellSurface.java:95) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.drawClaimingParticleO
nTopOfBlock(CellSurface.java:91) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.lambda$runClaimingPar
ticleOverSurfaceAtPlayer$0(CellSurface.java:44) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.scheduling.impl.FoliaTaskScheduler.lambd
a$runAsyncLater$10(FoliaTaskScheduler.java:110) ~[Towny.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncS
cheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:53
9) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:28:45 WARN]: [Towny] Async task for Towny v0.100.1.7 generated an exception
java.lang.IllegalStateException: Cannot retrieve chunk asynchronously
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72)
 ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockYAt(CraftWo
rld.java:995) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftRegionAccessor.getHighestBlockYA
t(CraftRegionAccessor.java:305) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockAt(CraftWor
ld.java:985) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at com.palmergames.bukkit.util.BlockUtil.getHighestNonLeafY(BlockUtil.ja
va:34) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.getParticleLocation(C
ellSurface.java:95) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.drawClaimingParticleO
nTopOfBlock(CellSurface.java:91) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.lambda$runClaimingPar
ticleOverSurfaceAtPlayer$0(CellSurface.java:44) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.scheduling.impl.FoliaTaskScheduler.lambd
a$runAsyncLater$10(FoliaTaskScheduler.java:110) ~[Towny.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncS
cheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:53
9) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:28:45 ERROR]: Thread Folia Async Scheduler Thread Timer failed main thread c
heck: Cannot retrieve chunk asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71)
 ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockYAt(CraftWo
rld.java:995) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftRegionAccessor.getHighestBlockYA
t(CraftRegionAccessor.java:305) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockAt(CraftWor
ld.java:985) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at com.palmergames.bukkit.util.BlockUtil.getHighestNonLeafY(BlockUtil.ja
va:34) ~[Towny.jar:?]
        at com.palmergames.bukkit.util.DrawUtil.runOnSurface(DrawUtil.java:39) ~
[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellBorder.runBorderedOnSurface(C
ellBorder.java:91) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.lambda$runClaimingPar
ticleOverSurfaceAtPlayer$3(CellSurface.java:49) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.scheduling.impl.FoliaTaskScheduler.lambd
a$runAsyncLater$10(FoliaTaskScheduler.java:110) ~[Towny.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncS
cheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:53
9) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:28:45 WARN]: [Towny] Async task for Towny v0.100.1.7 generated an exception
java.lang.IllegalStateException: Cannot retrieve chunk asynchronously
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72)
 ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockYAt(CraftWo
rld.java:995) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftRegionAccessor.getHighestBlockYA
t(CraftRegionAccessor.java:305) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.getHighestBlockAt(CraftWor
ld.java:985) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at com.palmergames.bukkit.util.BlockUtil.getHighestNonLeafY(BlockUtil.ja
va:34) ~[Towny.jar:?]
        at com.palmergames.bukkit.util.DrawUtil.runOnSurface(DrawUtil.java:39) ~
[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellBorder.runBorderedOnSurface(C
ellBorder.java:91) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.object.CellSurface.lambda$runClaimingPar
ticleOverSurfaceAtPlayer$3(CellSurface.java:49) ~[Towny.jar:?]
        at com.palmergames.bukkit.towny.scheduling.impl.FoliaTaskScheduler.lambd
a$runAsyncLater$10(FoliaTaskScheduler.java:110) ~[Towny.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncS
cheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:53
9) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>

### Towny version

0.100.1.7

### Server version

1.20.2 Folia

### Please use Pastebin.com to link the following files

a

**Comment by MrSugar08** [comment]
Ohh sory wrong issue type

**Comment by LlmDl** [comment]
For the time being you'll want to use the config to disable teh claiming particles.
