### ISSUE TITLE
Towny error

### ISSUE THREAD

**Issue by ddsb520** [TownyAdvanced/Towny#7253]
### What steps will reproduce the problem?

1.I replaced the original Leaves with Folia
2.I start server
3.I see this error

### What is the expected output?

Don't send me errors
better is to help me with this

### Towny version

0.100.1.13

### Server version

Folia 1.20.4

### Please use Pastebin.com to link the following files

 My error log:
[18:43:29 ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Accessing entity state off owning region's thread
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.4.jar:git-Folia-"5c17284"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftChicken.getHandle(CraftChicken.java:21) ~[folia-1.20.4.jar:git-Folia-"5c17284"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftChicken.getHandle(CraftChicken.java:6) ~[folia-1.20.4.jar:git-Folia-"5c17284"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isInWorld(CraftEntity.java:939) ~[folia-1.20.4.jar:git-Folia-"5c17284"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isValid(CraftEntity.java:393) ~[folia-1.20.4.jar:git-Folia-"5c17284"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.lambda$getLivingEntities$2(CraftRegionAccessor.java:321) ~[folia-1.20.4.jar:g
it-Folia-"5c17284"]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.getLivingEntities(CraftRegionAccessor.java:317) ~[folia-1.20.4.jar:git-Folia-
"5c17284"]
        at com.palmergames.bukkit.towny.tasks.MobRemovalTimerTask.run(MobRemovalTimerTask.java:96) ~[towny-0.100.1.13.jar:?]
        at com.palmergames.bukkit.towny.scheduling.impl.FoliaTaskScheduler.lambda$runRepeating$6(FoliaTaskScheduler.java:87) ~[towny-0.100.1
.13.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179
) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar
:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"5c17284"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:g
it-Folia-"5c17284"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.ja
r:git-Folia-"5c17284"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar
:git-Folia-"5c17284"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:43:29 WARN]: [Towny] Global task for Towny v0.100.1.13 generated an exception
java.lang.IllegalStateException: Accessing entity state off owning region's thread
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.4.jar:git-Folia-"5c17284"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftChicken.getHandle(CraftChicken.java:21) ~[folia-1.20.4.jar:git-Folia-"5c17284"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftChicken.getHandle(CraftChicken.java:6) ~[folia-1.20.4.jar:git-Folia-"5c17284"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isInWorld(CraftEntity.java:939) ~[folia-1.20.4.jar:git-Folia-"5c17284"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isValid(CraftEntity.java:393) ~[folia-1.20.4.jar:git-Folia-"5c17284"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.lambda$getLivingEntities$2(CraftRegionAccessor.java:321) ~[folia-1.20.4.jar:g
it-Folia-"5c17284"]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.getLivingEntities(CraftRegionAccessor.java:317) ~[folia-1.20.4.jar:git-Folia-
"5c17284"]
        at com.palmergames.bukkit.towny.tasks.MobRemovalTimerTask.run(MobRemovalTimerTask.java:96) ~[towny-0.100.1.13.jar:?]
        at com.palmergames.bukkit.towny.scheduling.impl.FoliaTaskScheduler.lambda$runRepeating$6(FoliaTaskScheduler.java:87) ~[towny-0.100.1
.13.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179
) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar
:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"5c17284"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:g
it-Folia-"5c17284"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.ja
r:git-Folia-"5c17284"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar
:git-Folia-"5c17284"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
My Latest Log
[latest.log.txt](https://github.com/TownyAdvanced/Towny/files/14278482/latest.log.txt)

I can't use Pastebin for some reasons
Please forgive me

**Comment by ddsb520** [comment]
To add, I deleted the original world and towny data , i can't see this error

**Comment by ddsb520** [comment]
i delete world and towny data , I also see this error
![image](https://github.com/TownyAdvanced/Towny/assets/96320440/f54bd4de-2f02-495d-84d6-9747a4dd4421)
